#!/usr/bin/env python3
"""PUT `CINE` ON THE EXPORT SURFACE. One name, no behaviour.

    python cineexport_build.py --src ../02-chain/sc-paradox.html \
                               --out ../02-chain/sc-paradox-cine.html

## Why this exists

`docs/RENDERER-BRIEF.md` §6: the post chain must ramp with the director's own
tier, so a fatal blow looks like one. `CINE` already knows all of it -- it
computes cuts, tiers, dilation and zoom before frame 1 -- and the renderer
reads it directly because they share one script scope.

Nothing OUTSIDE that scope can. The engine is a single classic script, so
`CINE`, `renderer` and `match` are top-level `const`: lexical globals, and
**not** properties of `window`. `renderer` was already on the export surface;
`CINE` was not, so the app harness reads `state.cine === null` and a post pass
that wants to ramp with the cut has nothing to ramp against.

## What it does NOT do

It adds a name to an object literal. It does not read `CINE`, write `CINE`,
move a number, or touch a draw call. `engine_ab` must therefore come back
2760/2760, and if it does not, this builder did something it did not intend to
and the answer is to find out what -- not to accept it because the change
"looks harmless".

## The one thing to be careful about

An exported object is exported BY REFERENCE. Anything holding `AC.CINE` can
write to it. The director's own law is that it may not change who wins, and
that survives -- `CINE` owns time scale, camera and mix, none of which the sim
reads. But an outside writer CAN change the picture, and a picture the app
shows that the mp4 will not is the exact fault `docs/ARCHITECTURE.md` §1 was
built to prevent. Read it. Do not write it from outside the engine.
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
PROTECTED = "sundered-crown.html"

STAMP = ("<!-- GENERATED by cineexport_build.py --src %SRC% "
         "— do not hand-edit or tune in place -->\n")

EDITS = [
    ("CINE on the export surface",
     '''              newMatch, __inject, SFX, renderer, IC,''',
     '''              newMatch, __inject, SFX, renderer, IC,
              /* THE DIRECTOR, FOR READING. `renderer` has always been here;
                 `CINE` was not, and outside this script there is no other way
                 to reach it -- the engine is one classic script, so every
                 top-level `const` is a lexical global and NOT a property of
                 `window`. `window.CINE` is undefined while `CINE` is alive,
                 which reads like the engine failed to boot.

                 The post chain (docs/RENDERER-BRIEF.md §6) needs it to ramp
                 bloom and aberration with the cut rather than applying them
                 flat. Everything it needs is already on this object while a
                 cut runs: `CINE.cut` carries `.tier`, `.fatal` and `.P`, the
                 tier's own lead/dropFrom/dropTo/ramp, assigned in CINE.begin.

                 EXPORTED BY REFERENCE, SO IT IS WRITABLE. Do not write it
                 from outside. The director may not change who wins and that
                 still holds -- it owns time scale, camera and mix and the sim
                 reads none of them -- but an outside writer can change the
                 PICTURE, and an app showing a picture the mp4 will not is the
                 fault docs/ARCHITECTURE.md §1 exists to prevent. */
              CINE,''')
]


def one(src: str, old: str, new: str, label: str) -> str:
    n = src.count(old)
    if n != 1:
        raise SystemExit(
            f"ANCHOR {label}: expected exactly 1 occurrence, found {n}.\n"
            f"  The source has moved under this builder. Do not weaken the\n"
            f"  anchor -- find out what changed.\n"
            f"  NOTE: if you are on Windows and this says 0 for an anchor you\n"
            f"  can see in the file, check the read encoding before the anchor.\n"
            f"  anchor head: {old.splitlines()[0][:90]!r}")
    print(f"  ok    {label}")
    return src.replace(old, new, 1)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="../02-chain/sc-paradox.html")
    ap.add_argument("--out", default="../02-chain/sc-paradox-cine.html")
    A = ap.parse_args()

    src_p = (HERE / A.src).resolve()
    out_p = (HERE / A.out).resolve()
    if out_p.name == PROTECTED:
        raise SystemExit("refusing to write the live build")
    if not src_p.exists():
        raise SystemExit(f"no such build: {src_p}")

    s0 = src_p.read_text(encoding="utf-8")
    s = s0
    print("\nCINEEXPORT BUILD -- one name on the export surface, no behaviour")
    print(f"  src {src_p.name}  {hashlib.sha256(s0.encode()).hexdigest()[:16]}")

    if "window.AC" not in s0:
        raise SystemExit("this source has no export surface to add to")
    if "\n              CINE," in s0:
        raise SystemExit("this source already exports CINE -- already built")
    if "const CINE" not in s0:
        raise SystemExit("this source has no CINE to export -- wrong build in "
                         "the chain? cinema_build.py adds the director.")

    for label, old, new in EDITS:
        s = one(s, old, new, label)

    s = STAMP.replace("%SRC%", src_p.name) + s

    # A BUILDER SHOULD SYNTAX-CHECK ITS OWN OUTPUT (CLAUDE.md §4.11). An
    # unbalanced insert has surfaced here before only as a twenty-second
    # Playwright timeout, which reads as a hang and not as a typo.
    if s.count("/*") != s.count("*/"):
        raise SystemExit(f"unbalanced block comments: {s.count('/*')} /* "
                         f"against {s.count('*/')} */")

    out_p.write_text(s, encoding="utf-8", newline="\n")
    h = hashlib.sha256(s.encode()).hexdigest()[:16]
    print(f"  out {out_p.name}  {h}   ({len(s) - len(s0):+d} bytes)")
    print("\n  NEXT, and none of it is optional:")
    print(f"    python engine_ab.py --a {A.src} --b {A.out} --n 9")
    print(f"    python verify.py --game {A.out} --n 40")
    print("    then re-run frame_build.py to carry the tip forward.\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
