#!/usr/bin/env python3
"""CARRY DAYBREAK'S CORONA TO THE TIP. One chain link, art only.

    python daybreak_annulus_build.py --src ../02-chain/sc-paradox-readouts.html \
                                     --out ../02-chain/sc-paradox-dawn.html
    python post_build.py --src ../02-chain/sc-paradox-dawn.html \
                         --out ../02-chain/sc-paradox-frame.html

WHY THIS EXISTS RATHER THAN A REBUILD FROM ultdawn_build.py
-----------------------------------------------------------
`ultdawn_build.py` OWNS this art and has been corrected -- that is where
CLAUDE.md 4.9 says a change lives, and any future rebuild from sc-crucible
carries it. But the chain from there to the tip cannot be replayed: most files
in 02-chain/ stamp `GENERATED by introcard_build.py` with NO `--src`, so the
build graph is not reconstructible from the tree, and reconstructing it by
guess on the build of record is how a session invalidates the whole history.
So the corrected block is carried forward one link instead.

THERE IS EXACTLY ONE COPY OF THE ART AND THIS FILE IS NOT IT. The block and
its marker are IMPORTED from ultdawn_build, and so is its brace-matching
replace. Restating them here is the drift CLAUDE.md 4.10 warns about: two
copies of one set-piece, and the tip quietly keeping the old one.

THIS CHANGES THE PICTURE AND NOTHING ELSE. `drawUltOver` is presentation --
nothing in Fighter, Match or Sfx reads it -- so engine_ab against the previous
tip must come back IDENTICAL on all 25 relics. If it does not, this build is
wrong and the diff is the proof.
"""
from __future__ import annotations
import argparse, pathlib, sys

HERE = pathlib.Path(__file__).parent
sys.path.insert(0, str(HERE))

from ultdawn_build import OVER_MARK, OVER_NEW, replace_block

STAMP = ("<!-- GENERATED by daybreak_annulus_build.py --src %SRC% "
         "— do not hand-edit or tune in place -->\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
            formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", default="../02-chain/sc-paradox-readouts.html")
    ap.add_argument("--out", default="../02-chain/sc-paradox-dawn.html")
    A = ap.parse_args()

    src = (HERE / A.src).resolve()
    out = (HERE / A.out).resolve()
    s = src.read_text(encoding="utf8")

    # The tip carries the OLD marker -- `/* ---- Daybreak: ...` -- because
    # ultdawn_build already replaced Judgement's block on the way through.
    # Match on what is actually in the source, not on what ultdawn started from.
    TIP_MARK = ('    /* ---- Daybreak: white heat radiating off the whole relic '
                '------------- */\n    else if (u.w === "dawnbringer"){')
    if TIP_MARK not in s:
        sys.exit("! Daybreak's block is not in --src in the shape expected. "
                 "Nothing written.")
    if 'c.arc(src.x, src.y, R * 0.94, TAU, 0, true)' in s:
        sys.exit("! --src already carries the annulus. Nothing to do.")

    block = CORONA_NEW
    n = s.count('c.createRadialGradient(src.x, src.y, 2, src.x, src.y, R * 2.3 * pulse)')
    s2 = replace_block(s, TIP_MARK, block, "Daybreak corona")
    if s2 == s:
        sys.exit("! replace_block was a no-op. Nothing written.")

    s2 = STAMP.replace("%SRC%", src.name) + s2

    # 4.11 -- A BUILDER SHOULD SYNTAX-CHECK ITS OWN OUTPUT. An unbalanced brace
    # here surfaces only as a twenty-second Playwright timeout somewhere else.
    body = s2[s2.index("<script"):]
    if body.count("{") != body.count("}"):
        sys.exit("! brace count in the output does not balance. Nothing written.")

    out.write_text(s2, encoding="utf8")
    print(f"  {out.name}")
    print(f"    corona discs before: {n}, after: "
          f"{s2.count('c.createRadialGradient(src.x, src.y, 2, src.x, src.y, R * 2.3 * pulse)')}")
    print(f"    annulus arcs: {s2.count('c.arc(src.x, src.y, R * 0.94, TAU, 0, true)')}")


if __name__ == "__main__":
    main()
