#!/usr/bin/env python3
"""Falsify the claim that an ENGINE change left the existing roster alone.

`ab_check.py` answers "is the phone build the same game" and is hardcoded to
that pair of files and to whatever roster each one happens to carry. That is
the wrong instrument for a variant that ADDS a relic: the two files no longer
have the same roster, so `AC.WEAPONS.map(w => w.id)` diverges and the sweeps
are not comparable at all.

This one takes two files and an EXPLICIT roster, so the question it asks is the
one that actually matters when the engine grows:

    the six shipped relics must be byte-identical, field for field, on the
    same seeds, on a build that now contains a projectile system

If a new object, a new tick, or a stray `this.rng()` draw has perturbed the
simulation for a match that contains no bow at all, this is what says so. The
bow doc names this explicitly: spawn projectiles from the existing per-step RNG
draw order or from a pure hash, and re-run the A/B to prove the six existing
relics are unchanged.

  python3 engine_ab.py --b sundered-crown-bow.html --n 200
  python3 engine_ab.py --a sundered-crown.html --b sundered-crown-vigil.html \
                       --ids dawnbringer,widowmaker,grudgebearer,thornwake,gravemourn,spellbreaker

Note the vigil variant will NOT pass this: it deliberately changes shipped
relics (Dawnbringer loses lifesteal, greatswords gained `mode:"swing"`). That
is a design change, not an engine change, and it is the distinction this tool
exists to make visible.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import time

from scpage import game

HERE = pathlib.Path(__file__).parent

SIX = "dawnbringer,widowmaker,grudgebearer,thornwake,gravemourn,spellbreaker"

# The roster is passed IN rather than read from the page, which is the whole
# point: both files must run the same pairings even though one of them has more
# relics than the other. Seeds are generated by an LCG inside the page so the
# two runs cannot drift through Python-side float or ordering differences.
SWEEP_JS = r"""
([ids, n, seed0]) => {
  const have = new Set(AC.WEAPONS.map(w => w.id));
  const missing = ids.filter(i => !have.has(i));
  if (missing.length) return { missing };
  const out = [];
  let s = seed0 >>> 0;
  for (let i = 0; i < ids.length; i++)
    for (let j = i + 1; j < ids.length; j++)
      for (let k = 0; k < n; k++) {
        s = (Math.imul(s, 1103515245) + 12345) >>> 0;
        out.push(AC.simulate(ids[i], ids[j], s));
      }
  return { rows: out };
}
"""


def sweep(path: pathlib.Path, ids: list[str], n: int, seed0: int):
    t0 = time.time()
    with game(game_path=path) as (page, errors):
        res = page.evaluate(SWEEP_JS, [ids, n, seed0])
        errs = list(errors)
    if res.get("missing"):
        print(f"  {path.name:<30} FAIL — roster is missing {res['missing']}")
        return None, errs
    rows = res["rows"]
    print(f"  {path.name:<30} {len(rows):>5} matches  {time.time()-t0:>5.1f}s"
          + (f"  !! {len(errs)} page errors" if errs else ""))
    return rows, errs


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--a", default="sundered-crown.html", help="control build")
    ap.add_argument("--b", required=True, help="variant build")
    ap.add_argument("--ids", default=SIX, help="comma-separated roster to compare")
    ap.add_argument("--n", type=int, default=200, help="seeds per pairing")
    ap.add_argument("--seed", type=int, default=20260812)
    a = ap.parse_args()

    ids = [s.strip() for s in a.ids.split(",") if s.strip()]
    pa, pb = HERE / a.a, HERE / a.b
    for p in (pa, pb):
        if not p.exists():
            print(f"! missing {p}")
            return 2

    pairings = len(ids) * (len(ids) - 1) // 2
    print(f"=== ENGINE A/B: {len(ids)} relics, {a.n} seeds x {pairings} pairings ===\n")
    a_rows, a_err = sweep(pa, ids, a.n, a.seed)
    b_rows, b_err = sweep(pb, ids, a.n, a.seed)
    print()
    if a_rows is None or b_rows is None:
        return 1

    ok = True
    if a_err or b_err:
        ok = False
        print(f"  FAIL  no page errors  — {a.a} {len(a_err)}, {a.b} {len(b_err)}")
        for e in (a_err + b_err)[:4]:
            print(f"          {e}")
    else:
        print("  PASS  no page errors on either build")

    if len(a_rows) != len(b_rows):
        print(f"  FAIL  same number of matches  — {len(a_rows)} vs {len(b_rows)}")
        return 1
    print(f"  PASS  same number of matches  — {len(a_rows)}")

    diffs = [(i, x, y) for i, (x, y) in enumerate(zip(a_rows, b_rows)) if x != y]
    if diffs:
        ok = False
        print(f"  FAIL  every match identical field for field  — {len(diffs)} differ")
        for i, x, y in diffs[:3]:
            print(f"          #{i}\n            control {json.dumps(x)}"
                  f"\n            variant {json.dumps(y)}")
    else:
        print(f"  PASS  every match identical field for field  — "
              f"{len(a_rows)}/{len(a_rows)}")

    # A sweep that resolved nothing would also compare equal, so state the shape
    # of what was actually compared rather than trusting the equality. This is
    # the check that stops a broken harness from reading as a clean result.
    winners = {r["winner"] for r in a_rows}
    durs = [r["duration"] for r in a_rows]
    seeds = {r["seed"] for r in a_rows}
    shape_ok = (len(winners) == len(ids)
                and len(seeds) > len(a_rows) * 0.9
                and min(durs) > 0)
    if not shape_ok:
        ok = False
    print(f"  {'PASS' if shape_ok else 'FAIL'}  the sweep is real  — "
          f"{len(winners)}/{len(ids)} distinct winners, {len(seeds)} distinct seeds, "
          f"{min(durs):.1f}-{max(durs):.1f}s")

    print("\n" + (f"ENGINE A/B PASS — {a.b} does not move the {len(ids)}-relic roster."
                  if ok else "ENGINE A/B FAIL"))
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
