#!/usr/bin/env python3
"""A TRUE STUN TURNS THE CRUCIBLE'S BLACK HOLE OFF.

    python forgehold_build.py --src ../02-chain/sc-paradox-arc.html \
                              --out ../02-chain/sc-paradox-crucible.html

Rick, 2026-08-29: *"currently when its true stunned it black hole effect still
happens. a true stun should turn it off."*

He is right and it was never wired. The forge tick opens with `f.stun = 0` --
the wheel cannot be stopped, argued out when the sweep was measured never
arriving -- and that line erases a TRUE stun exactly as readily as a hitstun.
So Grudgebearer went on dragging its quarry across the floor while it was
rooted, hexed or held in a Stasis field.

## What it is worth, measured before it was built

`tools/forgestun_probe.py` wraps `breakSpin`, this engine's true-stun marker,
and counts. 576 fights, 819 Crucible casts:

    foe            casts  stunned    rate   mean t   strike  fizzle
    axiom             42       36  85.7%     1.27       40       2
    spellbreaker      46       38  82.6%     1.28       44       2
    foregone          30       24  80.0%     1.58       29       1
    paradox           30       23  76.7%     2.01       24       6

    overall  121/819 casts eat a true stun (14.77%)
    288/481 stun events land after minT 1.05s
    20 of 24 relics never true-stun a lit Crucible at all

Four pairings, four fifths of the time, and nothing anywhere else.

## WHICH OF THE THREE READINGS THIS IS -- Rick chose, and it is the mildest

Offered cancel-the-cast (mirroring `breakSpin` on Bloodmill's wind-up), pull-off
with the window still running, and pull-off with the window PAUSED. He took the
third: *"Pull off, clock pauses."*

So this is a DELAY and nothing is lost. While the hold runs:

  * the pull does not act -- no acceleration, no infall blend;
  * `ultForge.t` does not advance, so the cast still gets its full `cap`
    seconds of pull, `minT` still has to be cleared before the hammer can
    connect, and the crit arm is delayed with it;
  * the set-piece fades off and its own clock stops with the forge's, so a
    paused Crucible does not quietly spend the 4.4s of `ultFx.life` it needs
    to still be on screen afterwards.

## WHAT IT DELIBERATELY DOES NOT DO

**THE WHEEL STILL TURNS.** `f.stun = 0` is untouched. Rick's sentence names the
black hole and nothing else, and the line it would have to cross is separately
argued: *"an ultimate made of rotation that a stun can hold still is a promise
the screen breaks."* A held Crucible therefore keeps swinging and can still
land -- which is what "nothing is lost" means. If the wheel should stop too,
that is a second decision and Rick's to make.

## THE SECOND SOURCE OF TRUTH, AND WHY THERE HAD TO BE ONE

v39 refused a parallel `hardStun` clock: *"the two would drift the first time
somebody added a stun."* That argument still holds and this does not break it.
`forgeHold` is NOT a stun clock -- it is the Crucible's own record of what the
pull owes, written at exactly the sites that write a true stun and nowhere
else, read only inside the forge tick, and zeroed when the forge lights. The
reason it cannot simply read `f.stun` is the first paragraph of this file: the
forge erases `f.stun` one step later, so by the time anything could look, there
is nothing there.

It is written through `breakSpin`, which is already the ONE hook every true
stun calls. A duration argument, and the four sites that pass one are exactly
the four that were already marking themselves. `windCap` passes none, because
running out of runway is not a stun.

## Gates

    engine_ab   MUST DIFFER on grudgebearer vs axiom / spellbreaker /
                foregone / paradox, and MUST NOT on anything else -- twenty
                relics never reach this code.
    verify      the gate. Four pairings move.
    forgestun_probe  re-run: the incidence is unchanged (this changes what a
                     stun DOES, not how often one lands).
"""
from __future__ import annotations

import argparse
import pathlib

HERE = pathlib.Path(__file__).resolve().parent

STAMP = "<!-- GENERATED by forgehold_build.py --src %SRC% -->\n"

# ---------------------------------------------------------------- 1. the field
OLD_FIELD = """    this.ultForge = null;     // {t, minT, cap} while the Crucible is lit"""
NEW_FIELD = """    this.ultForge = null;     // {t, minT, cap} while the Crucible is lit
    /* HOW LONG THE CRUCIBLE'S PULL IS OFF FOR. Not a stun clock and not a
       second one: the forge tick zeroes `stun` every frame so the wheel keeps
       turning, which leaves nothing for anything to read. This is written
       only where a TRUE stun is written -- through `breakSpin`, the single
       hook all four of them already call -- read only by the forge tick, and
       zeroed when the forge lights. Zero on every relic but one. */
    this.forgeHold = 0;"""

# ------------------------------------------------------------- 2. the one hook
OLD_HOOK = """  breakSpin(f, reason){
    if (!f.ultSpin) return;"""
NEW_HOOK = """  breakSpin(f, reason, trueFor){
    /* THE HOOK IS NOW READ BY TWO ULTIMATES. It has always been the marker
       that separates a true stun from ordinary hitstun -- the wind-up is
       simply the first thing that asked. `trueFor` is how long that stun
       runs, passed by the four application sites that mean one and omitted by
       `windCap`, which is a fighter running out of runway rather than a
       fighter being stunned.

       ORDER MATTERS: the Crucible has to be held BEFORE the early return,
       because Grudgebearer has no wind-up to break and would otherwise fall
       out of this function having been told nothing. */
    if (trueFor !== undefined && f.ultForge)
      f.forgeHold = Math.max(f.forgeHold, trueFor);
    if (!f.ultSpin) return;"""

# --------------------------------------------------- 3. the four calling sites
OLD_HEX = """        this.breakSpin(f, "the hex takes the wind out of it");"""
NEW_HEX = """        this.breakSpin(f, "the hex takes the wind out of it",
                       STATUS.hex.stunFor);"""

OLD_PIN = """      this.breakSpin(foe, "held in the field");"""
NEW_PIN = """      this.breakSpin(foe, "held in the field", u.pin);"""

OLD_FREEZE = """      this.breakSpin(foe, "rooted mid-wind-up");   // a TRUE stun"""
NEW_FREEZE = """      this.breakSpin(foe, "rooted mid-wind-up", u.freeze);   // a TRUE stun"""

OLD_HARROW = """      this.breakSpin(foe, "the blades burst and the wind goes out of it");"""
NEW_HARROW = """      this.breakSpin(foe, "the blades burst and the wind goes out of it",
                     u.stunBase + u.stunPer * n);"""

# ------------------------------------------------------------ 4. the forge tick
OLD_TICK = """      const F = f.ultForge, u = f.w.ult;
      F.t += dt;
      /* The wheel cannot be stopped. Hitstun and hex would stall the sweep
         past its own cap on seeds where the foe pounds the wielder — measured
         before this line existed: the strike simply never came. An ultimate
         made of rotation that a stun can hold still is a promise the screen
         breaks, so while the forge is lit the stun burns off. */
      f.stun = 0;"""
NEW_TICK = """      const F = f.ultForge, u = f.w.ult;
      /* The wheel cannot be stopped. Hitstun and hex would stall the sweep
         past its own cap on seeds where the foe pounds the wielder — measured
         before this line existed: the strike simply never came. An ultimate
         made of rotation that a stun can hold still is a promise the screen
         breaks, so while the forge is lit the stun burns off.

         DELIBERATELY ABOVE THE HOLD BELOW, AND DELIBERATELY UNCONDITIONAL.
         Rick's sentence names the black hole; a held Crucible keeps swinging
         and can still land, which is what makes the hold a delay rather than
         a cancellation. */
      f.stun = 0;
      /* A TRUE STUN TURNS THE BLACK HOLE OFF. Rick, 2026-08-29: "currently
         when its true stunned it black hole effect still happens. a true stun
         should turn it off."

         The pull stops and BOTH clocks stop with it — the forge's and the
         set-piece's — so the cast is delayed and nothing is spent. It still
         owes its full `cap` seconds of pull, `minT` still has to be cleared
         before the hammer can connect, and the crit arm waits with it.
         Offered cancel-the-cast and pull-off-while-the-window-runs as well;
         this is the reading Rick chose.

         Measured: 121 of 819 casts eat a true stun, and 20 of the 24 other
         relics can never do it — this is Axiom, Spellbreaker, Foregone and
         Paradox, and nobody else. tools/forgestun_probe.py.

         `dim` is presentation only and is eased in tickPresentation rather
         than snapped here: hex re-stuns every 1.15s for 0.20s, so a hard cut
         would strobe the whole set-piece three times in one cast and read as
         dropped frames rather than as a stun. */
      const X = this.ultFx;
      const mine = X && X.kind === "forge" && X.phase === "wind"
                     && X.src === (f === this.a ? "a" : "b");
      if (f.forgeHold > 0){
        f.forgeHold = Math.max(0, f.forgeHold - dt);
        if (mine) X.held = true;
        return;
      }
      if (mine) X.held = false;
      F.t += dt;"""

# ------------------------------------------- 5. the cast zeroes its own hold
OLD_CAST = """      f.ultForge = { t: 0, minT: u.minT || 1.0, cap: u.cap || 4.0 };
      this.ultFx = { w: f.w.id, kind: "forge", phase: "wind","""
NEW_CAST = """      f.ultForge = { t: 0, minT: u.minT || 1.0, cap: u.cap || 4.0 };
      /* A NEW CAST OWES NOTHING. One place to clear it rather than one at
         each of the three ways a Crucible can end. */
      f.forgeHold = 0;
      this.ultFx = { w: f.w.id, kind: "forge", phase: "wind", dim: 1,"""

# -------------------------------------------------- 6. the presentation clock
OLD_PRES = """    if (this.ultFx){
      this.ultFx.t += dt;
      if (this.ultFx.t > this.ultFx.life) this.ultFx = null;
    }"""
NEW_PRES = """    if (this.ultFx){
      /* A HELD CRUCIBLE DOES NOT AGE. Its clock is stopped in the forge tick,
         so if the set-piece kept aging it would run out its `life` while the
         cast it belongs to was still standing there — the black hole would
         come back from the hold invisible. Every other ultimate leaves `held`
         undefined and is untouched.

         `dim` eases over 0.10s instead of cutting, so three hex stuns inside
         one cast read as the forge being snuffed and relit rather than as
         three dropped frames. Presentation only: nothing in the simulation
         reads either field. */
      if (!this.ultFx.held) this.ultFx.t += dt;
      if (this.ultFx.dim !== undefined)
        this.ultFx.dim = clamp(this.ultFx.dim
                               + (this.ultFx.held ? -dt : dt) / 0.10, 0, 1);
      if (this.ultFx.t > this.ultFx.life) this.ultFx = null;
    }"""

# ------------------------------------------------------- 7. the two wind layers
# Both branches scale EVERY alpha they set by `r`, so `dim` folded into `r` is
# the whole set-piece -- glow, horizon, streamers, the wheel of heat, the dust --
# and nothing else in either function can see it. The two `r` lines are
# character-identical, so each anchor carries its own `pulse` line to tell them
# apart.
OLD_UNDER = """        const r = clamp(u.t / 1.6, 0, 1);
        const pulse = 0.85 + 0.15 * Math.sin(u.t * 9);"""
NEW_UNDER = """        /* `dim` folds into `r`, which every alpha in this branch is already
           scaled by, so a held Crucible takes the floor pool and the
           accretion with it. `=== undefined` and not `||`: dim is a number a
           hold can legitimately drive to 0 (CLAUDE.md §4.3). */
        const r = clamp(u.t / 1.6, 0, 1) * (u.dim === undefined ? 1 : u.dim);
        const pulse = 0.85 + 0.15 * Math.sin(u.t * 9);"""

OLD_OVER = """        const r = clamp(u.t / 1.6, 0, 1);
        const pulse = 0.9 + 0.1 * Math.sin(u.t * 11);"""
NEW_OVER = """        /* Same fold as the under-layer: the glow, the event horizon, the
           lensed rim, the streamers, the wheel of heat and the dust down the
           pull are all scaled by `r`, so this one term is the black hole
           going out. */
        const r = clamp(u.t / 1.6, 0, 1) * (u.dim === undefined ? 1 : u.dim);
        const pulse = 0.9 + 0.1 * Math.sin(u.t * 11);"""


def one(src: str, old: str, new: str, label: str) -> str:
    n = src.count(old)
    if n != 1:
        raise SystemExit(
            f"ANCHOR {label}: expected exactly 1 occurrence, found {n}.\n"
            f"  The source has moved under this builder. Do not weaken the\n"
            f"  anchor -- find out what changed.")
    print(f"  ok    {label}")
    return src.replace(old, new, 1)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="../02-chain/sc-paradox-arc.html")
    ap.add_argument("--out", default="../02-chain/sc-paradox-crucible.html")
    A = ap.parse_args()

    src_p = (HERE / A.src).resolve()
    out_p = (HERE / A.out).resolve()
    if not src_p.exists():
        print(f"! {src_p} does not exist")
        return 2
    s = src_p.read_text(encoding="utf-8")
    if "forgeHold" in s:
        print("! this builder has already run on the source. Build from the "
              "link before it.")
        return 2

    print(f"forgehold_build  {src_p.name} -> {out_p.name}")
    s = one(s, OLD_FIELD,  NEW_FIELD,  "the fighter carries a forge hold")
    s = one(s, OLD_HOOK,   NEW_HOOK,   "breakSpin takes the stun's duration")
    s = one(s, OLD_HEX,    NEW_HEX,    "site 1/4  hex")
    s = one(s, OLD_PIN,    NEW_PIN,    "site 2/4  the Stasis hold")
    s = one(s, OLD_FREEZE, NEW_FREEZE, "site 3/4  the root")
    s = one(s, OLD_HARROW, NEW_HARROW, "site 4/4  the Harrowing's burst")
    s = one(s, OLD_TICK,   NEW_TICK,   "the pull and the clock both stop")
    s = one(s, OLD_CAST,   NEW_CAST,   "a new cast owes nothing")
    s = one(s, OLD_PRES,   NEW_PRES,   "a held set-piece does not age")
    s = one(s, OLD_UNDER,  NEW_UNDER,  "the wind art, under-layer")
    s = one(s, OLD_OVER,   NEW_OVER,   "the wind art, over-layer")

    for marker, what in (("SWBFx", "the fx module"),
                         ("const ULTFX", "the fx glue"),
                         ("ULTFX.sync(m)", "the fx hook"),
                         ("SWBPost", "the post chain"),
                         ("baseHP: 400", "the pace change"),
                         ("Math.max(0, f.pinV[1])", "the stasis hold fix"),
                         ("GRAVITY STILL ACTS", "gravity through hit stop"),
                         ("dmg:23.50", "the grudgebearer nerf")):
        if marker not in s:
            raise SystemExit(f"! {what} ({marker!r}) is not in the output -- "
                             f"an upstream insert was lost.")
        print(f"  ok    carried: {what}")

    body = s.split("\n", 1)[1] if s.startswith("<!-- GENERATED") else s
    out_p.write_text(STAMP.replace("%SRC%", src_p.name) + body,
                     encoding="utf-8")
    print(f"\nwrote {out_p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
