#!/usr/bin/env python3
"""PUT THE PARTICLE FIELDS IN THE BUILD, so the mp4 gets what the lab showed.

    python fx_build.py --src ../02-chain/sc-paradox-frame.html \
                       --out ../02-chain/sc-paradox-fx.html

## Why this is the last step and not the first

`docs/RENDERER-BRIEF.md` §5: *"Iterate in the app. When Rick approves it, the
builder puts it in the chain. Do not write the builder first."* He has now
approved three times off played clips -- particles at all ("3 for sure"), the
vocabulary across four shapes ("the louder one is better every time"), and the
density ("dont push it further than this. but it looks good") -- and then the
whole roster. The look is settled, so this is the step that makes it real.

Until this runs, the fields exist only inside `ult_particle_lab.py` and no clip
that ships has them.

## What it inserts

1. `src/render/fx.js`, INLINE. The build is one self-contained HTML file with
   no `<script src>` and no dependency the game did not have -- the rule that
   keeps all 211 tools working -- so the module is pasted in rather than
   linked. Byte for byte the file the app loads; the sha256 is printed and
   stamped so a drift is visible rather than silent.

2. `ULTFX`, about twenty lines of glue: one field, the cast edge, and the
   sim-time sync.

3. ONE hook, at the end of `Renderer.drawUltOver`. That is the correct layer
   and not a convenience: `readouts_build.py` split the floats, tags and HUD
   out of the bloom's source on purpose (`docs/RENDER-LAYERS.md` §4), so a
   field drawn after `AC.__draw` would land on the wrong side of that split
   and the bloom would never see it.

## The two things that would have made this wrong

**A CAST IS AN EDGE, NOT A STATE.** `ultFx` persists for `life` seconds and is
advanced by the decay paths, so a field respawned whenever `ultFx` is truthy
would restart every frame. The edge is a change of owner or `u.t` running
backwards -- the same detection `ult_camera_probe.py` had to make, and for the
same reason.

**THE HOOK RUNS TWICE PER COMPOSITED FRAME.** With the post chain on, every
frame is drawn twice: readouts pass, then world pass. `post_build.py` had to
fix exactly this for the camera shake, and it presented as juddering PHYSICS
rather than as a drawing bug. `SWBFx` cannot have it: `stepTo` integrates to an
absolute sim time, so the second call is a no-op. That is why the field is aged
off `ultFx.t` and not off a per-frame delta.

## What it does NOT touch

The simulation. `ultFx` is presentation-only -- the engine says so where the
block is built: *"Presentation only: nothing in the simulation reads it."* --
and `drawUltOver` is a `Renderer` method. So `engine_ab` is expected to come
back identical, and if it does not, something here is wrong rather than
interesting.
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent
FX_JS = REPO / "src" / "render" / "fx.js"

STAMP = ("<!-- GENERATED by fx_build.py --src %SRC% "
         "(src/render/fx.js sha256 %SHA%) -->\n")

GLUE = r"""
/* ---------------------------------------------------- THE ULT FIELDS ---
   One field, driven off the ultimate's own clock. GENERATED by
   tools/fx_build.py; the module above is src/render/fx.js verbatim.

   PRESENTATION ONLY. Nothing here is read by the simulation, `ultFx` is
   already presentation-only by the engine's own comment, and drawUltOver is a
   Renderer method -- so engine_ab must come back identical. */
const ULTFX = {
  field: (typeof SWBFx !== "undefined") ? SWBFx.create() : null,
  key: null,
  on: true,

  /* Called from the end of drawUltOver, which the post chain runs TWICE per
     composited frame. Safe because stepTo() integrates to an ABSOLUTE sim
     time: the second call in a frame does nothing. */
  sync(m){
    const F = this.field, u = m && m.ultFx;
    if (!F || !this.on) return null;
    if (!u){ if (this.key !== null){ F.clear(); this.key = null; } return null; }
    const spec = SWBFx.SPECS[u.w];
    if (!spec){ if (this.key !== null){ F.clear(); this.key = null; } return null; }
    /* A CAST IS AN EDGE. ultFx persists for `life` seconds, so testing
       truthiness would respawn the field every frame; the edge is a change of
       owner, or u.t running backwards because a new cast reset it. */
    const key = u.w + "|" + u.src;
    if (key !== this.key || u.t + 1e-9 < F.t){
      F.spawn(spec, SWBFx.castSeed(m.seed, u),
              { x: u.x, y: u.y, tx: u.tx, ty: u.ty,
                radius: u.radius || 220 }, 1);
      this.key = key;
    }
    F.stepTo(u.t, CONFIG.physics.dt);
    return F;
  },
};
"""

# The tail of drawUltOver. Anchored on the closing `c.restore(); }` plus the
# comment that follows it, because `c.restore();\n  }` alone appears all over
# the renderer and a weak anchor is how a builder inserts into the wrong method
# and says nothing.
HOOK_OLD = """    c.restore();
  }

  /* ----------------------------------------------------------- fighter --- */"""

HOOK_NEW = """    c.restore();
    /* THE PARTICLE FIELD, last inside the ult's own layer -- over the
       fighters, under the HUD. Drawn here rather than after AC.__draw
       because readouts_build.py split the readouts out of the bloom's
       source on purpose (docs/RENDER-LAYERS.md 4); a later overlay would
       sit on the wrong side of that split and never bloom. */
    if (typeof ULTFX !== "undefined"){
      const F = ULTFX.sync(m);
      if (F){
        const at = F.spec && F.spec.mode === "burst" ? [u.tx, u.ty]
                                                     : [u.x, u.y];
        F.draw(c, at[0], at[1], u.aff);
      }
    }
  }

  /* ----------------------------------------------------------- fighter --- */"""


def one(src: str, old: str, new: str, label: str) -> str:
    n = src.count(old)
    if n != 1:
        raise SystemExit(
            f"ANCHOR {label}: expected exactly 1 occurrence, found {n}.\n"
            f"  The source has moved under this builder. Do not weaken the\n"
            f"  anchor -- find out what changed.\n"
            f"  anchor head: {old.splitlines()[0][:90]!r}")
    print(f"  ok    {label}")
    return src.replace(old, new, 1)


def main() -> int:
    ap = argparse.ArgumentParser()
    # THE DEFAULTS ARE THE CHAIN OF RECORD. post_build.py's went stale the day
    # ultcarry_build.py was inserted ahead of it, and three documents then
    # described the resulting trap as live for several sessions after it was
    # fixed. These point at the current tip and its successor; if this builder
    # ever stops being last, they have to move in the same commit.
    ap.add_argument("--src", default="../02-chain/sc-paradox-frame.html")
    ap.add_argument("--out", default="../02-chain/sc-paradox-fx.html")
    ap.add_argument("--off", action="store_true",
                    help="insert the fields but leave them switched off, for "
                         "an A/B that is one line rather than two builds")
    A = ap.parse_args()

    src_p = (HERE / A.src).resolve()
    out_p = (HERE / A.out).resolve()
    if not src_p.exists():
        print(f"! {src_p} does not exist")
        return 2
    if not FX_JS.exists():
        print(f"! {FX_JS} does not exist")
        return 2

    module = FX_JS.read_text(encoding="utf-8")
    mod_hash = hashlib.sha256(module.encode("utf-8")).hexdigest()
    s0 = src_p.read_text(encoding="utf-8")
    s = s0

    if "SWBFx" in s0:
        print("! the source already contains SWBFx -- this builder has "
              "already run on it.\n  Re-running would insert a second copy. "
              "Build from the link before it.")
        return 2

    print(f"fx_build  {src_p.name} -> {out_p.name}")

    anchor = "const renderer = new Renderer(cv);"
    block = ("/* ---- src/render/fx.js, inlined by fx_build.py. sha256:"
             + mod_hash + " ---- */\n"
             + module.rstrip() + "\n"
             + GLUE.strip() + "\n"
             + ("ULTFX.on = false;\n" if A.off else "")
             + "\n" + anchor)
    s = one(s, anchor, block, "the module and the glue")
    s = one(s, HOOK_OLD, HOOK_NEW, "the hook at the end of drawUltOver")

    s = STAMP.replace("%SRC%", src_p.name).replace("%SHA%", mod_hash[:16]) + s

    # A BUILDER SHOULD SYNTAX-CHECK ITS OWN OUTPUT -- CLAUDE.md 4.11. An
    # unbalanced `*/` once surfaced only as a twenty-second Playwright timeout.
    if s.count("/*") != s.count("*/"):
        raise SystemExit(f"unbalanced block comments: {s.count('/*')} vs "
                         f"{s.count('*/')}")
    if s.count("{") != s.count("}"):
        raise SystemExit(f"unbalanced braces: {s.count('{')} vs "
                         f"{s.count('}')}")
    if len(re.findall(r"\bSWBFx\b", s)) < 3:
        raise SystemExit("the module did not land")

    out_p.write_text(s, encoding="utf-8", newline="\n")
    print(f"  out {out_p.name}  "
          f"{hashlib.sha256(s.encode()).hexdigest()[:16]}"
          f"   ({len(s) - len(s0):+d} bytes)"
          f"   fields {'OFF' if A.off else 'ON'}")
    print(f"  module sha256 {mod_hash}  (must match src/render/fx.js)")
    print("\n  NEXT, and none of it is optional:")
    print(f"    python engine_ab.py --a {A.src} --b {A.out} --n 9"
          f"   # EXPECT IDENTICAL")
    print(f"    python verify.py --game {A.out} --n 40")
    print(f"    python chain_audit.py --tip {A.out} --builder fx_build.py")
    print(f"    python render_ab.py --a {A.src} --b {A.out}"
          f"   # EXPECT A DIFF\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
