#!/usr/bin/env python3
"""EXPERIMENT ARMS FOR THE FACTOR TEST. Builds variants of sc-r15.html in which
the 3x3 block's ULTIMATES and/or STATUSES are matched across the two schools.

    python3 gs_arm_build.py --ult   --out sc-armU.html    # ultimates matched
    python3 gs_arm_build.py --status --out sc-armS.html   # statuses matched
    python3 gs_arm_build.py --ult --status --out sc-armUS.html   # both

WHAT THIS IS FOR
----------------
`sundered-crown-factor-result.md` measured sanct/dwarv tuned-damage ratios of
0.69 / 0.98 / 1.05 on greatsword / bow / warhammer and could not name a cause.
It rejected the ultimate on the grounds that "Aureole heals 28 and shows no
depression" — but Ironhail, the control that argument leans on, has an ultimate
that deals **dmg 0**. Two anomalies in one column can cancel. The ultimate is
confounded with school across the whole block, so it has to be removed by
construction, not by argument.

The matched ultimate is deliberately the most neutral one the engine can
express: `kind:"beam"` with NO radius (so `inRange` is always true and the
result cannot depend on how far apart that type fights), no heal, no knock, no
apply, no volley. Every `charge` seconds it deals a fixed `dmg` and nothing
else. All six get the identical object.

The matched status is `sunder:1` — the dwarven one — chosen because it is what
Ironhail's comment already calls "the only status that cannot confound a 'did
the shot land' measurement".

--ult --status together makes the two relics in each column MECHANICALLY
IDENTICAL. That build is not an arm, it is the pipeline's self-test: if the
measurement still reports a school difference there, the measurement is broken.
`--selftest` checks exactly that, by trajectory identity rather than by
statistics.

This reads sc-r15.html and writes a NEW file. It never edits in place, and it
stamps its own GENERATED marker so tune.py --apply refuses it.
"""
from __future__ import annotations
import argparse, json, pathlib, re, sys

BLOCK = {
    "greatsword": ("dawnbringer", "emberedge"),
    "bow":        ("aureole",     "ironhail"),
    "warhammer":  ("censer",      "grudgebearer"),
}
BLOCK_IDS = [w for p in BLOCK.values() for w in p]

# The neutral ultimate. charge 15 is the median of the six it replaces
# (14,14,14,15,15,15); dmg 14 is near their mean (18,17,15,0,12,14 -> 12.7).
MATCHED_ULT = ('ult:{ name:"Testament", charge:15, kind:"beam", dmg:14, '
               'tip:"Shaft of light: 14 damage" }')
MATCHED_ONHIT = 'onHit:{ sunder:1 }'

MARK = "<!-- GENERATED by gs_arm_build.py — factor-test experiment arm -->"
SRC_MARK = "<!-- GENERATED by roster15_build.py"

# Stats that are supposed to be fixed by the TYPE. Checked, not assumed:
# the whole experiment rests on the two relics in a column differing ONLY in
# school, so this is the assumption most worth trying to break.
TYPE_STATS = ["reach", "width", "artW", "spin", "mode", "mass", "arc",
              "knockMul", "blades", "shot"]


def replace_field(text, wid, pattern, repl, label):
    i = text.find(f'id:"{wid}"')
    if i < 0:
        raise SystemExit(f"! no relic {wid}")
    j = text.find('blurb:', i)
    if j < 0:
        raise SystemExit(f"! no blurb terminator for {wid}")
    seg, k = re.subn(pattern, repl, text[i:j], count=1, flags=re.S)
    if k != 1:
        raise SystemExit(f"! {wid}: expected one {label}, found {k}")
    return text[:i] + seg + text[j:]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="sc-r15.html")
    ap.add_argument("--out", required=True)
    ap.add_argument("--ult", action="store_true")
    ap.add_argument("--status", action="store_true")
    ap.add_argument("--noheal", action="store_true",
                    help="strip heal: from the two block ultimates that have "
                         "one (Dawnbringer 34, Aureole 28), touching nothing "
                         "else — attribution within the ultimate")
    ap.add_argument("--dmg", default=None,
                    help="JSON {id: dmg} written into the block relics")
    a = ap.parse_args()
    if not (a.ult or a.status or a.dmg or a.noheal):
        raise SystemExit("! nothing to do — pass --ult/--status/--noheal/--dmg")

    root = pathlib.Path(__file__).parent.parent
    src = root / a.src
    out = root / a.out
    if out.name == "sundered-crown.html" or out.resolve() == src.resolve():
        raise SystemExit("! refusing to overwrite the source or the ship build")
    t = src.read_text(encoding="utf-8")
    if SRC_MARK not in t:
        raise SystemExit(f"! {a.src} is not the roster15 build")

    if a.ult:
        for wid in BLOCK_IDS:
            t = replace_field(t, wid, r"ult:\{.*?\},\n", MATCHED_ULT + ",\n", "ult:")
        print(f"  [arm] ultimate matched on {len(BLOCK_IDS)} relics: {MATCHED_ULT}")
    if a.status:
        for wid in BLOCK_IDS:
            t = replace_field(t, wid, r"onHit:\{[^}]*\}", MATCHED_ONHIT, "onHit:")
        print(f"  [arm] onHit matched on {len(BLOCK_IDS)} relics: {MATCHED_ONHIT}")
    if a.noheal:
        for wid in ("dawnbringer", "aureole"):
            t = replace_field(t, wid, r"\s*heal:\s*[0-9.]+,", "", "heal:")
        print("  [arm] heal stripped from Dawnbringer and Aureole; every other "
              "field of every ultimate untouched")
    if a.dmg:
        for wid, d in json.loads(pathlib.Path(a.dmg).read_text()).items():
            t = replace_field(t, wid, r"dmg:\s*[0-9.]+", f"dmg:{float(d):g}", "dmg:")
        print(f"  [arm] damage written from {a.dmg}")

    t = t.replace(SRC_MARK, MARK + "\n" + SRC_MARK, 1)
    out.write_text(t, encoding="utf-8")
    print(f"{a.src} -> {a.out}")

    # ---------------------------------------------------------- PREFLIGHT --
    from scpage import game
    with game(game_path=out.resolve()) as (pg, errs):
        report = pg.evaluate(
            """([block, typeStats, wantUlt, wantStatus, wantNoHeal]) => {
      const by = {}; for (const w of AC.WEAPONS) by[w.id] = w;
      const bad = [], note = [];
      // 1. the type stats really are identical down each column
      for (const [ty, pair] of Object.entries(block)){
        const [s, d] = [by[pair[0]], by[pair[1]]];
        for (const k of typeStats){
          const x = JSON.stringify(s[k]), y = JSON.stringify(d[k]);
          if (x !== y) bad.push(`${ty}: ${pair[0]}.${k}=${x} but ${pair[1]}.${k}=${y}`);
        }
      }
      // 2. matched fields really are matched, by deep compare not by regex faith
      const ids = Object.values(block).flat();
      if (wantUlt){
        const ref = JSON.stringify(by[ids[0]].ult);
        for (const id of ids) if (JSON.stringify(by[id].ult) !== ref)
          bad.push(`${id}: ult not matched -> ${JSON.stringify(by[id].ult)}`);
      }
      if (wantStatus){
        const ref = JSON.stringify(by[ids[0]].onHit);
        for (const id of ids) if (JSON.stringify(by[id].onHit || null) !== ref)
          bad.push(`${id}: onHit not matched -> ${JSON.stringify(by[id].onHit)}`);
        for (const id of ids) if (by[id].onSelf)
          bad.push(`${id}: has onSelf, which --status does not touch`);
      }
      if (wantNoHeal){
        for (const id of ids) if (by[id].ult.heal)
          bad.push(`${id}: ult still heals ${by[id].ult.heal}`);
        // and nothing ELSE about the ultimate may have moved
        for (const id of ids){
          const u = by[id].ult;
          if (!u.name || !u.tip || u.charge === undefined)
            bad.push(`${id}: ult mangled -> ${JSON.stringify(u)}`);
        }
      }
      // 3. a ranged relic with no shot block is the Aureole failure. Check the
      //    class of bug, not the one instance of it.
      for (const w of AC.WEAPONS)
        if (w.mode === 'ranged' && !w.shot) bad.push(`${w.id}: mode ranged, no shot block`);
      // 4. every block relic can fight, AND its ultimate actually fires and
      //    actually does something. An ult that silently no-ops would read as
      //    'neutralised' and be the same mistake in a new place.
      for (const id of ids){
        let fired = 0, dealt = 0, n = 0;
        for (const foe of ['thornwake','gravemourn','spellbreaker']){
          for (let k = 0; k < 6; k++){
            const m = new AC.Match(id, foe, 900 + k * 7919);
            const dt = AC.CONFIG.physics.dt; let g = 0;
            const me = m.a.w.id === id ? m.a : m.b, you = m.a.w.id === id ? m.b : m.a;
            let hpBefore = null, hpAfter = null, seen = 0;
            while (!m.over && g++ < 200000){
              const f0 = me.ultsFired, h0 = you.hp;
              m.step(dt);
              if (me.ultsFired > f0 && seen === 0){ seen = 1; hpBefore = h0; hpAfter = you.hp; }
            }
            fired += me.ultsFired; n++;
            if (hpBefore !== null) dealt += (hpBefore - hpAfter);
          }
        }
        note.push(`${id}: ${(fired/n).toFixed(2)} ults/match, first ult took ${(dealt/n).toFixed(1)} hp`);
        if (fired === 0) bad.push(`${id}: ultimate never fired in ${n} matches`);
      }
      return { bad, note, n: AC.WEAPONS.length };
    }""", [BLOCK, TYPE_STATS, bool(a.ult), bool(a.status), bool(a.noheal)])
        if errs:
            print("! PAGE ERRORS:\n  " + "\n  ".join(errs[:5]), file=sys.stderr)
            return 1
        for s in report["note"]:
            print("    " + s)
        if report["bad"]:
            print("! PREFLIGHT FAILED:\n  " + "\n  ".join(report["bad"]), file=sys.stderr)
            return 1
        print(f"  preflight OK: {report['n']} relics, type stats identical down "
              f"every column, ultimates fire and land")

        # 5. THE SELF-TEST. With ult AND status matched the two relics in a
        #    column differ only in name/colour, so at equal dmg they must
        #    produce byte-identical matches. If they do not, something in the
        #    sim reads the school and the whole experiment is void.
        if a.ult and a.status:
            same = pg.evaluate("""(block)=>{
              const by={}; for(const w of AC.WEAPONS) by[w.id]=w;
              const out=[];
              for (const [ty,[s,d]] of Object.entries(block)){
                const keep=[by[s].dmg, by[d].dmg];
                by[s].dmg = by[d].dmg = 17;
                let ok=0, tot=0;
                for (const foe of ['thornwake','gravemourn','widowmaker','farwarden'])
                  for (let k=0;k<8;k++){
                    const seed = 55555 + k*104729;
                    const ra = AC.simulate(s, foe, seed), rb = AC.simulate(d, foe, seed);
                    tot++;
                    if (ra.duration===rb.duration && ra.hp===rb.hp &&
                        ra.hits.a===rb.hits.a && ra.hits.b===rb.hits.b &&
                        ra.clanks===rb.clanks &&
                        (ra.winner===by[s].name)===(rb.winner===by[d].name)) ok++;
                  }
                by[s].dmg=keep[0]; by[d].dmg=keep[1];
                out.push([ty, ok, tot]);
              }
              return out; }""", BLOCK)
            allok = True
            for ty, ok, tot in same:
                print(f"    selftest {ty:<11} {ok}/{tot} matches byte-identical "
                      f"between the two schools at equal dmg")
                allok &= (ok == tot)
            if not allok:
                print("! SELFTEST FAILED — something in the sim reads the school",
                      file=sys.stderr)
                return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
