#!/usr/bin/env python3
"""GRAVITY KEEPS ACTING THROUGH HIT STOP, so a frozen arc is still an arc.

    python hitstop_build.py --src ../02-chain/sc-paradox-hold-clamp.html \
                            --out ../02-chain/sc-paradox-arc.html

Rick, 2026-08-29, on seed 1150834333: *"at 35 seconds grudgebearer is climbing
to its apex, accelerates unnaturally and then dive bombs to the ground. it may
not be a bug but its not how the games physics should function."*

He is right, and the measurement is unambiguous. Sampled at the sim's own
120 Hz through that climb, `dvy` is a constant +21.3 per step -- and then:

    t        y      dy       vy     dvy   hitStop
  34.658   419.5   -3.87   -463.7   +20.1    -
  34.675   415.7    0.00   -453.1   +10.6   0.080   FROZEN
  34.692   415.7    0.00   -453.1    +0.0   0.063   FROZEN
  34.708   415.7    0.00   -453.1    +0.0   0.047   FROZEN
  34.725   415.7    0.00   -453.1    +0.0   0.030   FROZEN
  34.742   415.7    0.00   -453.1    +0.0   0.013   FROZEN
  34.758   412.1   -3.69   -442.5   +10.6    -

## What is wrong with it

`step()` returns early while `hitStop` runs, so `move()` is never called and
NOBODY gets gravity -- including a ball in free flight on the far side of the
arena that had nothing to do with the impact. Grudgebearer was mid-arc; Paradox
cast its ultimate; the whole world froze for 0.083s.

The stall alone would be defensible -- it is the juice the config describes as
*"the single biggest contributor to hits feeling like they have weight."* The
part that is not defensible is that **velocity freezes too**. Over those
0.083s honest gravity would have taken Grudgebearer from -453 px/s to -351.
It resumes at -453: **102 px/s faster than its own arc allows.** It then climbs
higher than the arc permits and falls from a summit it should never have
reached. That is the "accelerates unnaturally, then dive bombs" exactly, and no
amount of it is visible in a position log, which is why every probe in this
repo has passed over it.

## The change, and it is one loop

Gravity is applied to `vy` during hit stop; position is NOT integrated. The
ball still stops dead for the punch, and it resumes on the velocity its
trajectory demands rather than the one it entered with. The arc is preserved
in shape while being displaced in time, which is what a freeze should do.

The mass term is copied from `move()` character for character. If the two ever
differ, a ball's fall rate changes depending on whether the world was frozen --
which is a subtler version of the bug this file exists to close.

## What it deliberately does NOT touch

**THE STASIS PIN.** `move()` opens with `if (f.pin > 0) return;` and says why:
*"a held ball does not accumulate fall either, so what it resumes with is what
it arrived with."* That is a designed hold with a captured resume vector
(`pinV`), argued out with Rick in v43 -- "no banked knockback and no loss of
momentum after the stun". Adding gravity there would bank 2 seconds of fall and
launch the quarry at ~2,450 px/s on release, which is a real dive bomb rather
than an apparent one. So the loop skips any fighter with `pin > 0`, and that
exclusion is the most important line in this builder.

## Gates

This touches the SIMULATION, so every trajectory in the game moves:

    engine_ab   MUST DIFFER, on every seed. That is the point.
    verify      the gate. Hit stop fires on every impact, so this shifts
                durations and winrates and both bands have to hold.
    the seed    1150834333 re-measured: dvy must stay constant THROUGH the
                freeze, and the apex must come down.
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent

STAMP = "<!-- GENERATED by hitstop_build.py --src %SRC% -->\n"

OLD = """    if (this.hitStop > 0){
      this.hitStop -= dt;
      this.t += dt;
      this.decayImpactOnly(dt);
      return;
    }"""

NEW = """    if (this.hitStop > 0){
      this.hitStop -= dt;
      this.t += dt;
      this.decayImpactOnly(dt);
      /* GRAVITY STILL ACTS, EVEN THOUGH NOTHING MOVES.

         Hit stop freezes the whole world, which is the point -- it is what
         makes a blow land. But it used to freeze VELOCITY too, and a ball in
         free flight somewhere else would come out of the freeze carrying the
         speed it went in with rather than the speed its arc had earned.
         Measured on seed 1150834333: Grudgebearer, mid-climb and nowhere near
         the impact, resumed at -453 px/s where honest gravity would have left
         it at -351. 102 px/s of phantom lift, a summit it should not have
         reached, and a fall from that summit that Rick read -- correctly -- as
         "accelerates unnaturally and then dive bombs".

         Position is still held. Only the velocity keeps earning what the
         clock owes it, so the arc is displaced in time instead of deformed.
         Invisible to every position log in this repo, which is why thirty
         probes and a 13/13 verify never saw it.

         THE PIN IS EXCLUDED AND THAT IS THE LOAD-BEARING LINE. `move` opens
         with `if (f.pin > 0) return;` because a held ball must resume with
         exactly what it was captured with -- Rick, v43: "no banked knockback
         and no loss of momentum after the stun." Two seconds of banked fall
         would launch a released quarry at ~2,450 px/s, which is the real
         version of the thing this change exists to remove.

         The mass term is `move`'s, character for character. If they ever
         differ, a ball falls at a different rate depending on whether the
         world happened to be frozen. */
      const HP = CONFIG.physics;
      for (const f of [this.a, this.b]){
        if (f.pin > 0) continue;
        f.vy += HP.gravity * Math.pow((f.w.mass + f.burden * f.burdenMass)
                                      / HP.massRef, HP.massWeight) * dt;
      }
      return;
    }"""


def one(src: str, old: str, new: str, label: str) -> str:
    n = src.count(old)
    if n != 1:
        raise SystemExit(
            f"ANCHOR {label}: expected exactly 1 occurrence, found {n}.\n"
            f"  The source has moved under this builder. Do not weaken the\n"
            f"  anchor -- find out what changed.")
    print(f"  ok    {label}")
    return src.replace(old, new, 1)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="../02-chain/sc-paradox-hold-clamp.html")
    ap.add_argument("--out", default="../02-chain/sc-paradox-arc.html")
    A = ap.parse_args()

    src_p = (HERE / A.src).resolve()
    out_p = (HERE / A.out).resolve()
    if not src_p.exists():
        print(f"! {src_p} does not exist")
        return 2
    s0 = src_p.read_text(encoding="utf-8")
    if "GRAVITY STILL ACTS" in s0:
        print("! this builder has already run on the source. Build from the "
              "link before it.")
        return 2

    print(f"hitstop_build  {src_p.name} -> {out_p.name}")
    s = one(s0, OLD, NEW, "gravity through hit stop, pins excluded")

    for marker, what in (("SWBFx", "the fx module"),
                         ("const ULTFX", "the fx glue"),
                         ("ULTFX.sync(m)", "the fx hook"),
                         ("SWBPost", "the post chain"),
                         ("baseHP: 400", "the pace change"),
                         ("Math.max(0, f.pinV[1])", "the stasis hold fix"),
                         ("dmg:23.50", "the grudgebearer nerf")):
        if marker not in s:
            raise SystemExit(f"! {what} ({marker!r}) is not in the output -- "
                             f"this builder ate an upstream edit.")
    print("  ok    upstream edits intact (post chain, fx, pace, balance)")

    s = STAMP.replace("%SRC%", src_p.name) + s

    if s.count("/*") != s.count("*/"):
        raise SystemExit(f"unbalanced block comments: {s.count('/*')} vs "
                         f"{s.count('*/')}")
    if s.count("{") != s.count("}"):
        raise SystemExit(f"unbalanced braces: {s.count('{')} vs {s.count('}')}")

    out_p.write_text(s, encoding="utf-8", newline="\n")
    print(f"  out {out_p.name}  "
          f"{hashlib.sha256(s.encode()).hexdigest()[:16]}"
          f"   ({len(s) - len(s0):+d} bytes)")
    print("\n  NEXT, and none of it is optional:")
    print(f"    python verify.py --game {A.out} --n 40")
    print(f"    python engine_ab.py --a {A.src} --b {A.out} --n 9"
          f"   # EXPECT A DIFF")
    print(f"    and re-measure seed 1150834333 through the freeze\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
