#!/usr/bin/env python3
"""PUT THE IGNITION OPEN IN THE BUILD, so the app and the mp4 both get it.

    python ignition_build.py --src ../02-chain/sc-paradox-crucible.html \
                             --out ../02-chain/sc-paradox-ignition.html

## Why this is the last step and not the first

`docs/RENDERER-BRIEF.md` §5: *"Iterate in the app. When Rick approves it, the
builder puts it in the chain. Do not write the builder first."*
`tools/ignition_lab.py` rendered four variants of one seed -- control, the
ignition alone, the opening camera alone, and both -- and Rick watched
`05-reference/v46-ignition/ignition-open-both-solo.mp4` and said make it
happen. So this ships the BOTH variant, and only that one.

Until this runs, the opening exists only inside the lab and no clip that ships
has it.

## What it inserts

1. `src/render/open.js`, INLINE. The build is one self-contained HTML file with
   no `<script src>` and no dependency the game did not have -- the rule that
   keeps every tool in `tools/` working -- so the module is pasted in rather
   than linked. Byte for byte the file the app loads; the sha256 is printed and
   stamped so a drift is visible rather than silent.

2. FOUR HOOKS, all of them in `Renderer.draw`, all of them one line:

     top of draw          SWBOpen.swell   the glow power-on, before anything
                                          is drawn and before the post chain's
                                          three inner passes, so all four
                                          agree on one multiplier
     the camera block     SWBOpen.cam     the opening owns the camera, ahead
                                          of CINE and ahead of the
                                          both-relics-must-fit clamp
     after POSTFX.frame   SWBOpen.flare   over the COMPOSITED frame
     end of draw          SWBOpen.flare   the same, on the chain-off path

## The three things that would have made this wrong

**THE CLAMP IS NOT A BUG AND IT IS NOT BEING REMOVED.** `Renderer.draw`'s
feasibility clamp -- both relics' magnified bodies must fit the usable frame --
is correct for every mid-fight cut, was built off a probe that found 8/8
wall-adjacent set-pieces clipping relic body, and stays exactly as it is. It is
also, precisely, why an opening shot could not exist before: at spawn
separation the two relics are ~503 su apart and the clamp pulls any asked zoom
back to ~1.0. So the opening does not ask CINE for a zoom that would be taken
away -- it computes its own transform and the renderer takes that branch
INSTEAD, for 2.35 seconds, and the lean clamp still applies inside it.

**THE FLARE MUST NOT BLOOM.** `fx_build.py` hooks inside `drawUltOver` so its
fields reach the bloom; this hooks after the composite so its flare does not,
because that is the picture Rick approved. A white core at 0.95 alpha handed to
the post chain is CLAUDE.md §4.1b and §4.1c happening for a third time.

**THE CLOCK IS `m.t`.** The lab drove the opening off wall time, which is
correct there and would be a defect here: the post chain draws every frame four
times, and the app's rAF and the capture's fixed cadence must produce the same
picture. Everything in `open.js` is a pure function of sim time, so the extra
passes are identity. This is the lesson `post_build.py` paid for in juddering
camera shake and `fx_build.py` paid for again.

## What it does NOT touch

The simulation. The camera is a transform, the swell is a `shadowBlur`
multiplier on the renderer's own canvases, the flare is drawn over a finished
frame. `engine_ab` must come back IDENTICAL, and if it does not, something here
is wrong rather than interesting.
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent
OPEN_JS = REPO / "src" / "render" / "open.js"

STAMP = ("<!-- GENERATED by ignition_build.py --src %SRC% "
         "(src/render/open.js sha256 %SHA%) -->\n")

# ------------------------------------------------------------------ hooks ---

# 1. THE SWELL, at the very top of draw, ahead of the post chain's hook so all
#    four passes of a composited frame see one multiplier.
SWELL_OLD = """  draw(m){
    /* THE POST CHAIN. One hook, at the top of the one method every path into"""

SWELL_NEW = """  draw(m){
    /* THE IGNITION OPEN'S GLOW POWER-ON. First thing, before the post chain's
       hook below, so the readouts, emissive, world and composite passes of one
       frame all draw at the same multiplier. A pure function of m.t, so the
       repeat calls are identity rather than four power-ons. */
    if (typeof SWBOpen !== "undefined") SWBOpen.swell(m, this);
    /* THE POST CHAIN. One hook, at the top of the one method every path into"""

# 2. THE FLARE on the post path -- over the composite, which is the whole
#    point, and the reason it is here rather than inside the emissive pass.
FLARE_POST_OLD = """    if (POSTFX.on && !POSTFX.busy && (this.roMode | 0) === 0){
      POSTFX.frame(this, m);
      return;
    }"""

FLARE_POST_NEW = """    if (POSTFX.on && !POSTFX.busy && (this.roMode | 0) === 0){
      POSTFX.frame(this, m);
      /* THE IGNITION FLARE, over the COMPOSITED frame. Not inside the emissive
         pass: the flare Rick approved is unbloomed, and a white core at 0.95
         alpha is exactly the input CLAUDE.md 4.1b and 4.1c are about. */
      if (typeof SWBOpen !== "undefined") SWBOpen.flare(m, this);
      return;
    }"""

# 3. THE CAMERA. The opening's branch goes FIRST and the existing CINE branch
#    becomes its else-if, untouched line for line.
CAM_OLD = """    if (typeof CINE !== "undefined" && CINE.on && CINE.zoom > 1.0001){
      let z = CINE.zoom, over = 1 + (CINE.overscan || 0);"""

CAM_NEW = """    /* THE OPENING OWNS THE CAMERA, and it is the one framing decision the
       clamp below must not make. See src/render/open.js: at spawn separation
       the both-relics-must-fit rule pulls any asked zoom back to ~1.0, which
       is correct for a cut and is why an opening shot could not exist. This
       branch runs for 2.35s of sim time at the top of a fight and then hands
       the lens back; CINE is neither read nor written by it. */
    const __open = (typeof SWBOpen !== "undefined")
      ? SWBOpen.cam(m, this, CONFIG.arena) : null;
    if (__open){
      c.translate(__open[0], __open[1]);
      c.scale(__open[2], __open[2]);
      c.translate(-__open[0], -__open[1]);
      this._cineFocus = [__open[0], __open[1]];
      this._cineCam = __open;
    } else if (typeof CINE !== "undefined" && CINE.on && CINE.zoom > 1.0001){
      let z = CINE.zoom, over = 1 + (CINE.overscan || 0);"""

# 4. THE FLARE on the chain-off path, at the end of draw. Guarded twice: the
#    post chain's three inner draws reach this line with `busy` set AND with a
#    non-zero roMode, and neither of them is the finished frame.
TAIL_OLD = """    c.restore();
    if (__sv){
      Object.assign(this, __sv);
      c.setTransform(this.k, 0, 0, this.k, 0, 0);
      if (__bg) this.drawScrunchPanel(m, __sk);
    }
  }"""

TAIL_NEW = """    c.restore();
    if (__sv){
      Object.assign(this, __sv);
      c.setTransform(this.k, 0, 0, this.k, 0, 0);
      if (__bg) this.drawScrunchPanel(m, __sk);
    }
    /* THE IGNITION FLARE with the chain off. The post path draws it after the
       composite instead; this line must not also fire for POSTFX's three inner
       passes, which is what both guards are for. */
    if (typeof SWBOpen !== "undefined" && !POSTFX.busy && (this.roMode | 0) === 0)
      SWBOpen.flare(m, this);
  }"""


def one(src: str, old: str, new: str, label: str) -> str:
    n = src.count(old)
    if n != 1:
        raise SystemExit(
            f"ANCHOR {label}: expected exactly 1 occurrence, found {n}.\n"
            f"  The source has moved under this builder. Do not weaken the\n"
            f"  anchor -- find out what changed.\n"
            f"  anchor head: {old.splitlines()[0][:90]!r}")
    print(f"  ok    {label}")
    return src.replace(old, new, 1)


def main() -> int:
    ap = argparse.ArgumentParser()
    # THE DEFAULTS ARE THE CHAIN OF RECORD. If this builder ever stops being
    # last, they move in the same commit -- post_build.py's went stale the day
    # something was inserted ahead of it and three documents then described a
    # dead trap as live.
    ap.add_argument("--src", default="../02-chain/sc-paradox-crucible.html")
    ap.add_argument("--out", default="../02-chain/sc-paradox-ignition.html")
    ap.add_argument("--off", action="store_true",
                    help="insert the opening but leave it switched off, for an "
                         "A/B that is one line rather than two builds")
    A = ap.parse_args()

    src_p = (HERE / A.src).resolve()
    out_p = (HERE / A.out).resolve()
    if not src_p.exists():
        print(f"! {src_p} does not exist")
        return 2
    if not OPEN_JS.exists():
        print(f"! {OPEN_JS} does not exist")
        return 2

    module = OPEN_JS.read_text(encoding="utf-8")
    mod_hash = hashlib.sha256(module.encode("utf-8")).hexdigest()
    s0 = src_p.read_text(encoding="utf-8")
    s = s0

    if "SWBOpen" in s0:
        print("! the source already contains SWBOpen -- this builder has "
              "already run on it.\n  Re-running would insert a second copy. "
              "Build from the link before it.")
        return 2

    print(f"ignition_build  {src_p.name} -> {out_p.name}")

    anchor = "const renderer = new Renderer(cv);"
    block = ("/* ---- src/render/open.js, inlined by ignition_build.py. sha256:"
             + mod_hash + " ---- */\n"
             + module.rstrip() + "\n"
             + ("SWBOpen.on = false;\n" if A.off else "")
             + "\n" + anchor)
    s = one(s, anchor, block, "the module")
    s = one(s, SWELL_OLD, SWELL_NEW, "the swell, at the top of draw")
    s = one(s, FLARE_POST_OLD, FLARE_POST_NEW, "the flare, over the composite")
    s = one(s, CAM_OLD, CAM_NEW, "the camera, ahead of CINE's branch")
    s = one(s, TAIL_OLD, TAIL_NEW, "the flare, chain-off path")

    s = STAMP.replace("%SRC%", src_p.name).replace("%SHA%", mod_hash[:16]) + s

    # A BUILDER SHOULD SYNTAX-CHECK ITS OWN OUTPUT -- CLAUDE.md 4.11. An
    # unbalanced `*/` once surfaced only as a twenty-second Playwright timeout.
    if s.count("/*") != s.count("*/"):
        raise SystemExit(f"unbalanced block comments: {s.count('/*')} vs "
                         f"{s.count('*/')}")
    if s.count("{") != s.count("}"):
        raise SystemExit(f"unbalanced braces: {s.count('{')} vs "
                         f"{s.count('}')}")
    if len(re.findall(r"\bSWBOpen\b", s)) < 6:
        raise SystemExit("the module or the hooks did not land")

    out_p.write_text(s, encoding="utf-8", newline="\n")
    print(f"  out {out_p.name}  "
          f"{hashlib.sha256(s.encode()).hexdigest()[:16]}"
          f"   ({len(s) - len(s0):+d} bytes)"
          f"   opening {'OFF' if A.off else 'ON'}")
    print(f"  module sha256 {mod_hash}  (must match src/render/open.js)")
    print("\n  NEXT, and none of it is optional:")
    print(f"    python engine_ab.py --a {A.src} --b {A.out} --n 9"
          f"   # EXPECT IDENTICAL")
    print(f"    python ignition_probe.py --game {A.out}"
          f"   # the picture, measured")
    print(f"    python verify.py --game {A.out} --n 40")
    print(f"    python chain_audit.py --tip {A.out} --builder ignition_build.py")
    print(f"    python render_ab.py --a {A.src} --b {A.out}"
          f"   # EXPECT A DIFF\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
