#!/usr/bin/env python3
"""THE MINUTE: the same fight stretched from ~48s to ~60s.

    python pace60_build.py --src ../02-chain/sc-lastthree.html \
                           --out ../02-chain/sc-minute.html

Rick, 2026-09-02: *"we also did some work to make fights last longer. id
really like to get the average closer to a minute. how do we achieve that."*
Cowork priced it in `06-docs/v65/pace-60-v65.md` and Rick ruled the cell the
same day: **S = H = 1.30**, and **accept the pairing ceiling, as before**.

    combat.baseHP    400 -> 520
    SECOND SEAL      t: 21 -> 27      collapse.startT 21 -> 27, WITH IT
    THIRD SEAL       t: 49 -> 64
    timeout          120 -> 156       a backstop, not a win condition

## This is pace_build.py's lever pulled a second time, not a new one

`pace_build.py` took the mean 37.3s -> ~49s by scaling HEALTH AND THE CLOCK
TOGETHER, and its reasoning is why this is a scale and not a knob: damage
escalates on a wall clock (x1.00, x1.35 at the Second Seal, x1.85 at the
Third), so health alone spends the extra fight inside the Third Seal at 1.85x
and changes the fight's SHAPE. Scaling the seals with the health keeps the
proportions and changes the length. v65 measured that again on the grid --
health-only (S 1.00, H 1.45) reaches 59.6s and the diagonal reaches 61.6s at
less health -- and the diagonal is the one that is the same fight.

## The numbers are the roster's, not ten pairings'

`pace_sweep.py` prices a cell on ten old pairings. `pace_roster_probe.py`
runs every pairing on the build, which is what "the average" means. All 528
pairings on the 33-relic build, 3 seeds, 1,584 fights a cell, on Chromium
141 in a Cowork container:

    S     H   baseHP  seals    t/o   mean   med   p90    max  t/out  ults
  1.00  1.00     400  21/49    120   47.5  47.7  60.3   79.9    0     4.2
  1.30  1.30     520  27/64    156   60.1  59.7  75.7  107.5    0     5.5

Duration goes roughly as scale^0.9 on the diagonal, because the escalated
acts still eat a growing share of the extra health.

## What it costs, and none of it is optional to know

- **THE PAIRING CEILING GETS WORSE.** The four relics already over verify's
  18-70s band -- Lightkeeper, Axiom, Farwarden, Spellbreaker -- run to ~100s
  against each other. verify's thirteenth check was already red at 74.8s and
  "accepted rather than fixed" (CLAUDE.md); at a 60s mean it is red by
  thirty seconds. **Rick ruled: accept, as before.** Do not read the red
  check as this build failing, and do not read it as green either.
- **Ults per fight 4.2 -> 5.5.** Charge is pure wall time, so a longer fight
  buys 1.3 more set-pieces for free. That is a change to the film's rhythm.
- **The music bed is 162s a match against 126s**, rendered offline at every
  match start. Same class of cost pace_build accepted at 130 against 90.
- **The balance drifts and v65 §4 names who**, at n~96 a relic (+/-5pp):
  Ravelbone and Marrowdraw down 16-20 points, Axiom up 17. Nothing outside
  30-70 at that sample and the spread NARROWS. Expect verify to want two or
  three damage touches, the way pace_build wanted Grudgebearer's -- and
  **that is verify's to say on the pinned runtime, not this builder's.** No
  damage number is touched here.

## Why the source is a flag and not a constant

v65 open decision 3 is which link carries this, and it was not settled when
the document was written because the chain tip (`sc-static`, Arclight) is
STOPPED at stage 4 on a ruling. Every anchor below is CONFIG and exists
identically in every link from `sc-paradox-pace.html` forward, so this
builder runs on any of them. It ships pointed at `sc-lastthree.html`
because that is the build the app loads and the build every number above
was measured on. Re-running it on a later tip is one flag.

## Gates

This touches the SIMULATION, so the expectation inverts the usual way:

    engine_ab   MUST DIFFER. Run it to see the direction, not to see a pass.
    verify      THE gate. Expect the duration band red and known (above).
    pace_roster_probe   the number Rick asked for, on the pinned runtime.
    chain_audit the upstream inserts -- fx, post chain, curse window, Scour.
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent

STAMP = "<!-- GENERATED by pace60_build.py --src %SRC% -->\n"

# (label, anchor, replacement). Every anchor is narrow enough to be unique
# and wide enough to name what it is -- `t: 21` alone appears all over a
# physics build, and a weak anchor is how a builder edits the wrong thing
# silently.
#
# THE ORDER OF THE TUPLE IS NOT COSMETIC. chain_audit.py discovers a builder's
# inserts by looking for a module-level table of tuples whose LAST element is a
# multi-line string, and it takes the label from the FIRST. pace_build.py's own
# `(old, new, label)` is therefore invisible to it -- and so was this file
# until the audit came back "no *_NEW inserts found ... which is itself a
# failure". That is open item 31's discovery being too narrow for the FIFTH
# time, in its cheapest costume yet: the tool cannot see a builder written the
# way the builder it is imitating was written. Note it, do not widen the tool
# from here -- a label like "grudgebearer dmg 27.93 -> 23.50" is over the
# length filter, so accepting single-line bodies would make every
# `(old, new, label)` builder report its LABELS as lost inserts.
EDITS = [
    ("baseHP 400 -> 520",
     "  combat:  { hitCd: 0.45, knock: 165, baseHP: 400 },",
     "  combat:  { hitCd: 0.45, knock: 165, baseHP: 520 },"),

    ("SECOND SEAL 21s -> 27s",
     '    { t: 21, name: "SECOND SEAL",',
     '    { t: 27, name: "SECOND SEAL",'),

    ("THIRD SEAL 49s -> 64s",
     '    { t: 49, name: "THIRD SEAL",',
     '    { t: 64, name: "THIRD SEAL",'),

    # The collapse is NOT an independent knob, and the comment above it
    # already says why. It has now moved twice for the same reason, so the
    # comment says that too -- a rule that has been applied twice is worth
    # more on the page than a rule that was stated once.
    ("the hall closes with the Second Seal, at 27s",
     "     is exactly the invisible correction this project deleted `seek` "
     "over. */\n"
     "  collapse: { startT: 21, rate: 4.2, maxInset: 140 },",

     "     is exactly the invisible correction this project deleted `seek` "
     "over.\n\n"
     "     THE SEAL HAS MOVED TWICE SINCE AND THIS NUMBER HAS MOVED WITH IT,\n"
     "     which is the whole point of the rule rather than an exception to\n"
     "     it: 15 -> 21 (pace_build.py, 2026-08-29) and 21 -> 27 here\n"
     "     (pace60_build.py, v65). A builder that scales the seals scales\n"
     "     this in the SAME edit, and this one refuses to write if the two\n"
     "     ever disagree. */\n"
     "  collapse: { startT: 27, rate: 4.2, maxInset: 140 },"),

    # THE COMMENT IS PART OF THE NUMBER. The one standing here was written
    # for 120 and cites a 1,200-fight sweep, a 76.6s maximum and a bed of
    # `CONFIG.timeout + intro.dur + 6` -- and `intro.dur` has not existed
    # since cardstrip_build.py removed the fight card. A comment defining
    # itself against numbers and fields that are gone is worse than none.
    ("timeout 120 -> 156 (a backstop, not a win condition)",
     "  /* RAISED, NOT DELETED, and it is a backstop rather than a mechanic.\n"
     "     Swept over 1,200 fights at baseHP 400 and seals 21/49: mean 49.3s,\n"
     "     p99 72.3, MAX 76.6, and 0.0% reached even the old 80. So the\n"
     "     timeout WIN is unreachable in practice -- which is what Rick asked\n"
     "     for -- but 76.6 against 80 was 4% of margin, which is not a\n"
     "     guarantee, it is a coincidence waiting to be reported as a bug.\n"
     "\n"
     "     Not deleted, for two reasons. A sim with no terminator is a HANG:\n"
     "     Match guards at 200,000 steps and returns `over` false, which\n"
     "     verify.py reads as an unresolved match and every capture tool reads\n"
     "     as a stall. And this number SIZES THE MUSIC BED -- `dur =\n"
     "     CONFIG.timeout + intro.dur + 6`, rendered through an\n"
     "     OfflineAudioContext at every match start -- so a huge value would\n"
     "     render minutes of audio per match to buy nothing. 120 is 57% above\n"
     "     the observed maximum and costs a 130s bed against 90. */\n"
     "  timeout: 120,",

     "  /* RAISED AGAIN, AND STILL A BACKSTOP RATHER THAN A MECHANIC. It is\n"
     "     on the wall clock like the seals and the collapse, so it takes the\n"
     "     same 1.30: 120 -> 156.\n"
     "\n"
     "     v65 measured the ROSTER rather than ten pairings -- all 528\n"
     "     pairings on the 33-relic build, 3 seeds, 1,584 fights at baseHP\n"
     "     520 and seals 27/64: mean 60.1s, median 59.7, p90 75.7, MAX\n"
     "     107.5, and 0 fights ended on the clock. So the timeout WIN is\n"
     "     still unreachable in practice, with 45% of margin over the longest\n"
     "     fight measured on this build.\n"
     "\n"
     "     Not deleted, for the same two reasons. A sim with no terminator is\n"
     "     a HANG: Match guards at 200,000 steps and returns `over` false,\n"
     "     which verify.py reads as an unresolved match and every capture\n"
     "     tool reads as a stall. And this number SIZES THE MUSIC BED --\n"
     "     `dur = CONFIG.timeout + 6`, rendered through an\n"
     "     OfflineAudioContext at every match start -- so it renders 162s of\n"
     "     audio a match against 126s. That is the same class of cost\n"
     "     pace_build accepted at 130 against 90.\n"
     "\n"
     "     AND THE MARGIN IS THINNER THAN THE MEAN SAYS, because what moved\n"
     "     most is the PAIRING ceiling: Lightkeeper, Axiom, Farwarden and\n"
     "     Spellbreaker run to ~100s against each other, and verify's\n"
     "     thirteenth check is red by thirty seconds rather than by five.\n"
     "     Rick ruled to accept that (v65 decision 2), as he did at 74.8s.\n"
     "     If those four are ever tuned, this is the number that reads the\n"
     "     result. */\n"
     "  timeout: 156,"),

    # PROSE THAT NAMES THE NUMBER MOVES WITH THE NUMBER. curse's `dur` 99 is
    # compared against the timeout to say the pool can outlive the status,
    # and the comparison is still true -- it is only the figure that goes
    # stale, which is exactly the drift CLAUDE.md keeps catching in comments.
    ("the curse-pool comment names the timeout",
     "           against a 120s timeout means this is reachable",
     "           against a 156s timeout means this is reachable"),
]

# Upstream inserts that must survive. chain_audit.py is the real check; these
# are the cheap ones, and they are here because this builder replaces spans in
# CONFIG on a link that carries four other builders' work.
MARKERS = [
    ("SWBFx", "the fx module"),
    ("const ULTFX", "the fx glue"),
    ("ULTFX.sync(m)", "the fx hook in drawUltOver"),
    ("SWBPost", "the post chain"),
    ("SWBOpen", "the ignition open"),
    ("tickScour", "Scour's tornado tick"),
    ("cursePool", "the curse pool"),
]


def one(src: str, old: str, new: str, label: str) -> str:
    n = src.count(old)
    if n != 1:
        raise SystemExit(
            f"ANCHOR {label}: expected exactly 1 occurrence, found {n}.\n"
            f"  The source has moved under this builder. Do not weaken the\n"
            f"  anchor -- find out what changed.\n"
            f"  anchor head: {old.splitlines()[0][:90]!r}")
    print(f"  ok    {label}")
    return src.replace(old, new, 1)


def seal_matches_collapse(s: str) -> tuple[float, float]:
    """The hall must start closing ON the Second Seal. The comment above
    `collapse` has said so since the seal first moved, and a rule that lives
    only in prose is a rule waiting to be broken by the next builder that
    scales one of the two. So it is asserted on the OUTPUT text."""
    seal = re.search(r'\{ t: ([\d.]+), name: "SECOND SEAL"', s)
    coll = re.search(r"collapse: \{ startT: ([\d.]+),", s)
    if not seal or not coll:
        raise SystemExit("! could not read the Second Seal or collapse.startT "
                         "back out of the output -- the edit landed somewhere "
                         "unexpected.")
    return float(seal.group(1)), float(coll.group(1))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="../02-chain/sc-lastthree.html",
                    help="the link this lands on; see the docstring, it is a "
                         "flag because v65 open decision 3 is not settled")
    ap.add_argument("--out", default="../02-chain/sc-minute.html")
    A = ap.parse_args()

    src_p = (HERE / A.src).resolve()
    out_p = (HERE / A.out).resolve()
    if not src_p.exists():
        print(f"! {src_p} does not exist")
        return 2

    s0 = src_p.read_text(encoding="utf-8")
    if "baseHP: 520" in s0 or "timeout: 156," in s0:
        print("! the source already carries the minute pace -- this builder "
              "has run on it.\n  Build from the link before it.")
        return 2
    if "baseHP: 400" not in s0:
        print("! the source is not on pace_build's numbers (no `baseHP: 400`)."
              "\n  This builder scales 400/21/49/120; it is not a general "
              "pace tool.")
        return 2

    s = s0
    print(f"pace60_build  {src_p.name} -> {out_p.name}   (S = H = 1.30)")
    for label, old, new in EDITS:
        s = one(s, old, new, label)

    for marker, what in MARKERS:
        if s.count(marker) < 1:
            raise SystemExit(f"! {what} ({marker!r}) is not in the output -- "
                             f"this builder ate an upstream insert.")
    print(f"  ok    upstream inserts intact ({len(MARKERS)} markers)")

    seal, coll = seal_matches_collapse(s)
    if seal != coll:
        raise SystemExit(f"! the hall does not close on the Second Seal: seal "
                         f"t={seal}, collapse.startT={coll}. That is the one "
                         f"rule the collapse comment states and it is not a "
                         f"preference.")
    print(f"  ok    the hall closes ON the Second Seal (both {seal:g}s)")

    s = STAMP.replace("%SRC%", src_p.name) + s

    # CLAUDE.md 4.11 -- a builder syntax-checks its own output.
    if s.count("/*") != s.count("*/"):
        raise SystemExit(f"unbalanced block comments: {s.count('/*')} vs "
                         f"{s.count('*/')}")
    if s.count("{") != s.count("}"):
        raise SystemExit(f"unbalanced braces: {s.count('{')} vs {s.count('}')}")

    out_p.write_text(s, encoding="utf-8", newline="\n")
    print(f"  out {out_p.name}  "
          f"{hashlib.sha256(s.encode()).hexdigest()[:16]}"
          f"   ({len(s) - len(s0):+d} bytes)")
    print("\n  NEXT, and none of it is optional:")
    print(f"    python verify.py --game {A.out} --n 40"
          f"        # THE gate. Duration band red and KNOWN")
    print(f"    python engine_ab.py --a {A.src} --b {A.out} --n 9"
          f"   # EXPECT A DIFF")
    print(f"    python pace_roster_probe.py --game {A.out} --cells 1.0:1.0 "
          f"--n 3   # ~60s, on the pinned runtime")
    # chain_audit's question here is whether THIS builder ate somebody
    # ELSE'S insert, so `--builder` is the UPSTREAM builder and `--relic` the
    # link that builder wrote. Pointing it at pace60_build.py with
    # `--relic <src>` asks whether inserts that are not in the source are in
    # the source, which is a green report about nothing.
    print(f"    python chain_audit.py --relic {A.src} --tip {A.out} "
          f"--builder duskreave_build.py   # and the other upstream builders")
    print("    and a fight WATCHED end to end in the app. This changes the "
          "length of every picture.\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
