#!/usr/bin/env python3
"""LONGER FIGHTS: more health, a later collapse, and no timeout win.

    python pace_build.py --src ../02-chain/sc-paradox-fx.html \
                         --out ../02-chain/sc-paradox-pace.html

Rick, 2026-08-29: *"lets try something simple. get rid of the timeout win, let
fights go to their full conclusion. increase the time it takes for the arena to
shrink and increase fighter hp across the board to achieve desired fight
length."* Target 45-60s against a measured 37.3s.

## The numbers, and they were swept rather than guessed

`tools/pace_sweep.py` over a 12-cell grid, then the chosen cell at 1,200
fights across ten pairings:

    baseHP        300 -> 400
    SECOND SEAL   t=15 -> 21     (and the hall starts closing with it)
    THIRD SEAL    t=35 -> 49
    timeout       80  -> 120

    mean 49.3s  median 50.2s  p90 63.3  p99 72.3  MAX 76.6  unresolved 0

## Why the seals move and not just the health

Damage escalates on a WALL CLOCK -- 1.00, then 1.35 at the Second Seal, then
1.85 at the Third. Raising health without moving the seals does not make a
longer fight of the same shape; it spends the extra health inside the Third
Seal at 1.85x damage, so duration rises much less than linearly and most of
the fight ends up in the escalated act. Scaling the clock WITH the health
keeps the proportions and changes the length, which is what "longer fights"
should mean. Measured: at the old seals, H=1.4 alone buys 38.0s -> 45.8s;
with the clock scaled too it reaches 49-51s at less health.

## Why `collapse.startT` is not set independently

The build says why, and it is a rule rather than a preference:

  > Starts on the Second Seal, not at an arbitrary clock time: the seal breaks
  > and the hall begins to close. [...] a wall that starts closing at an
  > unexplained clock time is exactly the invisible correction this project
  > deleted `seek` over.

So it moves to exactly `acts[1].t`. Rick asked for the arena to shrink later;
21s instead of 15s delivers that, and it keeps the reason on screen.

## Why the timeout is RAISED and not deleted

Rick asked for the timeout win gone, and at these numbers it already is: of
1,200 fights, **0.0% reached even the old 80s** and none were unresolved. But
the observed maximum is 76.6s, which is 4% under 80 -- far too thin to leave
as the thing standing between the roster and a fight that ends on a clock.

It is not deleted either, and there are two reasons:

1. **A sim with no terminator is a hang, not a long fight.** `Match` guards at
   200,000 steps; past that a match comes back with `over` false, which
   `verify.py`'s "every match resolved" check reads as a failure and every
   capture tool reads as a stall.
2. **`CONFIG.timeout` SIZES THE MUSIC BED.** `dur = CONFIG.timeout +
   intro.dur + 6`, rendered through an OfflineAudioContext at every match
   start. A timeout of 240 would render 250s of audio per match for no reason.

120 is 57% above the observed maximum and costs a 130s bed against today's 90.
The timeout win is unreachable in practice; the backstop still exists.

## Gates

This is the first change in this arc that touches the SIMULATION, so unlike
`fx_build.py` the expectation inverts:

    engine_ab   MUST DIFFER. This changes the fights on purpose. Run it to see
                the direction, not to see a pass.
    verify      the real gate: 300 pairings, and the winrate band is what a
                longer fight moves. Anything that banks or heals HP gains.
    chain_audit NOW MEANINGFUL. This is the first builder downstream of
                fx_build.py, so it is the first one that could eat the
                particle inserts. Check them.
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent

STAMP = "<!-- GENERATED by pace_build.py --src %SRC% -->\n"

# (anchor, replacement, label). Every one is narrow enough to be unique and
# wide enough to name what it is -- `t: 15` alone appears all over a physics
# build, and a weak anchor is how a builder edits the wrong thing silently.
EDITS = [
    ("  combat:  { hitCd: 0.45, knock: 165, baseHP: 300 },",
     "  combat:  { hitCd: 0.45, knock: 165, baseHP: 400 },",
     "baseHP 300 -> 400"),

    ('    { t: 15, name: "SECOND SEAL",',
     '    { t: 21, name: "SECOND SEAL",',
     "SECOND SEAL 15s -> 21s"),

    ('    { t: 35, name: "THIRD SEAL",',
     '    { t: 49, name: "THIRD SEAL",',
     "THIRD SEAL 35s -> 49s"),

    ("  collapse: { startT: 15, rate: 4.2, maxInset: 140 },",
     "  collapse: { startT: 21, rate: 4.2, maxInset: 140 },",
     "the hall closes with the Second Seal, at 21s"),

    # BALANCE, NOT PACING, AND IT IS HERE ONLY BECAUSE THE CHAIN CANNOT BE
    # REPLAYED. This number is OWNED by roster15_build.py, which is the root
    # of the chain, and it has been changed there too. It is duplicated here
    # because ultcarry_build.py exists precisely because some links cannot be
    # replayed to the tip, so "fix it at the source and rebuild" is not
    # available. Two files defining one number is the drift CLAUDE.md §4.9 is
    # about -- so each names the other, and roster15_build.py is the one that
    # is right if they ever disagree.
    #
    # 27.93 -> 23.50: the pace change put Grudgebearer at 62.8% (+/-2.5 over
    # 1,440 fights) because a longer fight suits a heavy hitter. 23.50 is
    # 53.8%, mid-roster against a spread of 43-58%.
    ('    blades:[0], reach:76, width:26, artW:54, dmg:27.93, spin:1.6,',
     '    blades:[0], reach:76, width:26, artW:54, dmg:23.50, spin:1.6,',
     "grudgebearer dmg 27.93 -> 23.50 (62.8% -> 53.8%)"),

    ("  timeout: 80,",
     "  /* RAISED, NOT DELETED, and it is a backstop rather than a mechanic.\n"
     "     Swept over 1,200 fights at baseHP 400 and seals 21/49: mean 49.3s,\n"
     "     p99 72.3, MAX 76.6, and 0.0% reached even the old 80. So the\n"
     "     timeout WIN is unreachable in practice -- which is what Rick asked\n"
     "     for -- but 76.6 against 80 was 4% of margin, which is not a\n"
     "     guarantee, it is a coincidence waiting to be reported as a bug.\n\n"
     "     Not deleted, for two reasons. A sim with no terminator is a HANG:\n"
     "     Match guards at 200,000 steps and returns `over` false, which\n"
     "     verify.py reads as an unresolved match and every capture tool reads\n"
     "     as a stall. And this number SIZES THE MUSIC BED -- `dur =\n"
     "     CONFIG.timeout + intro.dur + 6`, rendered through an\n"
     "     OfflineAudioContext at every match start -- so a huge value would\n"
     "     render minutes of audio per match to buy nothing. 120 is 57% above\n"
     "     the observed maximum and costs a 130s bed against 90. */\n"
     "  timeout: 120,",
     "timeout 80 -> 120 (a backstop, not a win condition)"),
]


def one(src: str, old: str, new: str, label: str) -> str:
    n = src.count(old)
    if n != 1:
        raise SystemExit(
            f"ANCHOR {label}: expected exactly 1 occurrence, found {n}.\n"
            f"  The source has moved under this builder. Do not weaken the\n"
            f"  anchor -- find out what changed.\n"
            f"  anchor head: {old.splitlines()[0][:90]!r}")
    print(f"  ok    {label}")
    return src.replace(old, new, 1)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="../02-chain/sc-paradox-fx.html")
    ap.add_argument("--out", default="../02-chain/sc-paradox-pace.html")
    A = ap.parse_args()

    src_p = (HERE / A.src).resolve()
    out_p = (HERE / A.out).resolve()
    if not src_p.exists():
        print(f"! {src_p} does not exist")
        return 2

    s0 = src_p.read_text(encoding="utf-8")
    s = s0
    if "baseHP: 400" in s0:
        print("! the source already has baseHP 400 -- this builder has run on "
              "it.\n  Build from the link before it.")
        return 2

    print(f"pace_build  {src_p.name} -> {out_p.name}")
    for old, new, label in EDITS:
        s = one(s, old, new, label)

    # THE PARTICLE INSERTS MUST SURVIVE. This is the first builder downstream
    # of fx_build.py, which is exactly the class chain_audit.py exists for: a
    # downstream builder replacing a span that contains someone else's edit,
    # and nothing failing. Cheap to assert here as well as there.
    for marker, what in (("SWBFx", "the fx module"),
                         ("const ULTFX", "the fx glue"),
                         ("ULTFX.sync(m)", "the fx hook in drawUltOver"),
                         ("SWBPost", "the post chain")):
        if s.count(marker) < 1:
            raise SystemExit(f"! {what} ({marker!r}) is not in the output -- "
                             f"this builder ate an upstream insert.")
    print("  ok    upstream inserts intact (post chain, fx module, glue, hook)")

    s = STAMP.replace("%SRC%", src_p.name) + s

    # CLAUDE.md 4.11 -- a builder syntax-checks its own output.
    if s.count("/*") != s.count("*/"):
        raise SystemExit(f"unbalanced block comments: {s.count('/*')} vs "
                         f"{s.count('*/')}")
    if s.count("{") != s.count("}"):
        raise SystemExit(f"unbalanced braces: {s.count('{')} vs {s.count('}')}")

    out_p.write_text(s, encoding="utf-8", newline="\n")
    print(f"  out {out_p.name}  "
          f"{hashlib.sha256(s.encode()).hexdigest()[:16]}"
          f"   ({len(s) - len(s0):+d} bytes)")
    print("\n  NEXT, and none of it is optional:")
    print(f"    python verify.py --game {A.out} --n 40"
          f"        # THE gate: winrate band")
    print(f"    python engine_ab.py --a {A.src} --b {A.out} --n 9"
          f"   # EXPECT A DIFF")
    print(f"    python pace_sweep.py --game {A.out} --scales 1.0 --hp 1.0"
          f"   # duration, as built\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
