#!/usr/bin/env python3
"""WHAT A STASIS HOLD RELEASES A BALL WITH. Two variants, for Rick to watch.

    python pinrelease_build.py --mode clamp   # never resume upward
    python pinrelease_build.py --mode drop    # no vertical at all

Rick, seed 1150834333: the quarry hangs dead still for two seconds and then
climbs. Measured: caught rising at 263 px/s, held 2.32s, resumed rising at
263 px/s. Store-and-release is working exactly as written -- the stored vector
is simply two seconds stale, and gravity is continuous.

Rick on the proposed fix: *"im worried that dropping the vertical is going to
cause more weird physics. i guess build it and let me look."* Which is a fair
worry and the reason there are two modes here rather than one.

## The two, and why `clamp` is the conservative one

    clamp   f.vy = Math.max(0, pinV[1])
            Only the case that looks wrong changes. A ball caught RISING
            resumes at rest and falls; a ball caught FALLING resumes at
            exactly the speed it was caught with, as today. Three of the four
            holds in Rick's seed are unaffected by this -- their captured vy
            was already downward.

    drop    f.vy = 0
            Every hold releases from rest, whichever way the ball was going.
            Cleaner as a rule, but it introduces a SECOND discontinuity to fix
            the first: a ball caught falling at 287 px/s now resumes at 0 and
            has to accelerate again, which is its own kind of hesitation. This
            is the mode Rick was worried about and he is right to be.

`vx` is untouched in both. The horizontal component of a stored velocity does
not go stale -- nothing acts on it during the hold -- so discarding it would
be throwing away the part of store-and-release that is correct.

## What is NOT changed

The banking rule. `move` still assigns rather than accumulates, so everything
that happened to the ball's velocity while it could not use it is still
discarded on release -- Rick, v43: *"no banked knockback and no loss of
momentum after the stun."* Verified: the banked vector survives exactly one
sim step and the ball never moves with it. This builder edits only WHICH
vector is restored, not whether the discard happens.

## Gates

Touches the simulation, so:

    engine_ab   MUST DIFFER
    verify      durations and winrates both move; a hold that releases at rest
                is a hold that ends with the quarry lower and slower
    and Rick watches a clip, because the entire question is what it looks like
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent

STAMP = "<!-- GENERATED by pinrelease_build.py --mode %MODE% --src %SRC% -->\n"

OLD = "    if (f.pinV){ f.vx = f.pinV[0]; f.vy = f.pinV[1]; f.pinV = null; }"

BODY = {
    "clamp": (
        "    if (f.pinV){\n"
        "      f.vx = f.pinV[0];\n"
        "      /* NEVER RESUME UPWARD. The stored vector is what the ball was\n"
        "         caught with, and horizontally that stays true -- nothing acts\n"
        "         on vx during a hold. Vertically it does not: gravity is\n"
        "         continuous, so a two-second-old climb is a claim about the\n"
        "         world that stopped being true one step into the hold.\n"
        "         Measured on seed 1150834333: caught rising at 263 px/s, held\n"
        "         2.32s, resumed rising at 263 px/s -- a ball hanging dead\n"
        "         still in the air and then accelerating upward.\n\n"
        "         Only the broken case moves. A quarry caught FALLING still\n"
        "         resumes at exactly its captured speed, which is three of the\n"
        "         four holds in that seed. A quarry caught RISING resumes at\n"
        "         rest and falls, which is what a held thing does when it is\n"
        "         let go.\n\n"
        "         The discard is untouched: this still ASSIGNS, so knockback\n"
        "         banked during the hold is still thrown away. v43's rule. */\n"
        "      f.vy = Math.max(0, f.pinV[1]);\n"
        "      f.pinV = null;\n"
        "    }"),
    "drop": (
        "    if (f.pinV){\n"
        "      f.vx = f.pinV[0];\n"
        "      /* RELEASE FROM REST, vertically. A thing held in place and let\n"
        "         go falls; it does not resume a journey it began three seconds\n"
        "         ago. Horizontal is kept because nothing acts on it during the\n"
        "         hold, so that half of the stored vector is still true.\n\n"
        "         THE COST, AND IT IS REAL: a ball caught FALLING at 287 px/s\n"
        "         now resumes at 0 and has to build the speed back. That is a\n"
        "         second discontinuity introduced to remove the first, and it\n"
        "         is why `clamp` exists beside this. Rick called it before it\n"
        "         was built: \"im worried that dropping the vertical is going to\n"
        "         cause more weird physics.\"\n\n"
        "         The discard is untouched: still an assignment, so banked\n"
        "         knockback is still thrown away. v43's rule. */\n"
        "      f.vy = 0;\n"
        "      f.pinV = null;\n"
        "    }"),
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=sorted(BODY), required=True)
    ap.add_argument("--src", default="../02-chain/sc-paradox-pace.html")
    ap.add_argument("--out", default=None)
    A = ap.parse_args()

    src_p = (HERE / A.src).resolve()
    out_p = (HERE / (A.out or f"../02-chain/sc-paradox-hold-{A.mode}.html")
             ).resolve()
    if not src_p.exists():
        print(f"! {src_p} does not exist")
        return 2

    s0 = src_p.read_text(encoding="utf-8")
    n = s0.count(OLD)
    if n != 1:
        print(f"! the pinV restore anchor appears {n} times, expected 1.\n"
              f"  Do not weaken it -- find out what changed.")
        return 2

    print(f"pinrelease_build --mode {A.mode}  {src_p.name} -> {out_p.name}")
    s = s0.replace(OLD, BODY[A.mode], 1)
    print(f"  ok    the pinV restore")

    for marker, what in (("SWBFx", "the fx module"), ("SWBPost", "the chain"),
                         ("baseHP: 400", "the pace change"),
                         ("dmg:23.50", "the balance number")):
        if marker not in s:
            print(f"! {what} ({marker!r}) missing -- ate an upstream edit")
            return 1
    print("  ok    upstream edits intact")

    s = STAMP.replace("%MODE%", A.mode).replace("%SRC%", src_p.name) + s
    if s.count("/*") != s.count("*/"):
        print(f"! unbalanced block comments")
        return 1
    if s.count("{") != s.count("}"):
        print(f"! unbalanced braces")
        return 1

    out_p.write_text(s, encoding="utf-8", newline="\n")
    print(f"  out {out_p.name}  {hashlib.sha256(s.encode()).hexdigest()[:16]}"
          f"   ({len(s)-len(s0):+d} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
