#!/usr/bin/env python3
"""PUT THE POST CHAIN IN THE BUILD, so the mp4 gets what the app shows.

    python post_build.py --src ../02-chain/sc-paradox-readouts.html \
                         --out ../02-chain/sc-paradox-post.html

## Why this is the last step and not the first

`docs/RENDERER-BRIEF.md` §5: *"Iterate in the app. When Rick approves it, the
builder puts it in the chain. Do not write the builder first."* He has now
approved four times -- bloom LOW, trails LONG, cut ramp GENTLE, grade MID --
each off a filmstrip, so the look is settled and this is the step that makes
it real.

Until this runs, the app has bloom and the video does not. That IS the
divergence `docs/ARCHITECTURE.md` §1 exists to prevent, and it has been true
of this repo all afternoon.

## What it inserts

1. `src/render/post.js`, INLINE. The build is one self-contained HTML file
   with no `<script src>` and no dependency the game did not have; that rule
   is why every one of the 195 tools still works, so the module is pasted in
   rather than linked. Byte-for-byte the same file the app loads -- if the two
   ever differ, the guarantee above is gone again and quietly.

2. `POSTFX`, twenty lines of glue: the offscreen WebGL canvas, the readout
   canvas, the state object, and `frame()`.

3. ONE hook, at the top of `Renderer.draw`. Every path into the picture goes
   through that method -- the live rAF loop, `AC.__draw`, and `CINE.drawLerped`
   -- so one insert catches all three and there is no second code path to keep
   in step.

## How the two passes reach one canvas

The renderer only ever draws to `#cv`, and `#cv` is a 2D canvas, so it cannot
also be the WebGL surface. `POSTFX.frame` therefore:

    roMode 2 -> draw -> copy #cv to the readout canvas
    roMode 1 -> draw -> #cv now holds the world
    post.render(#cv, state) -> composited into the offscreen GL canvas
    drawImage that back into #cv

`#cv` stays the single thing every tool reads -- `toDataURL` in cinema_clip,
verify's non-blank check, render_ab's hash. Nothing downstream learns a new
name. The cost is one extra full-frame copy, and tools/post_cost.py is where
that gets priced rather than assumed.

## What happens when WebGL is not there

`POSTFX.on` goes false and `draw` runs exactly as it did before. A machine
without WebGL2 gets the old picture rather than no picture -- and it says so
once in the console, because a silent fallback is how you ship a clip that is
missing an effect and never find out.
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent
POST_JS = REPO / "src" / "render" / "post.js"
PROTECTED = "sundered-crown.html"

STAMP = ("<!-- GENERATED by post_build.py --src %SRC% "
         "— do not hand-edit or tune in place -->\n")

GLUE = r'''
/* ==========================================================================
   THE POST CHAIN, IN THE BUILD.  GENERATED by tools/post_build.py
   ==========================================================================

   The module above (SWBPost) is byte-for-byte src/render/post.js, the same
   file app/ui/post-dev.js loads. That is not tidiness: if the app's copy and
   the build's copy ever differ, the app shows Rick something the mp4 will not,
   which is the one fault docs/ARCHITECTURE.md §1 was written to prevent.

   THE SETTINGS ARE NOT HERE. They are SWBPost.SPREAD.DEFAULT and friends,
   inside the module, chosen off filmstrips in 05-reference/post/. A second
   copy of "which bloom" living in this glue is how a build ends up shipping
   something nobody picked.

   The simulation cannot see any of this. POSTFX reads the renderer's layout
   and CINE's cut state and writes neither. */
const POSTFX = {
  on: false,
  post: null,
  gl: null,
  ro: null,
  roCtx: null,
  busy: false,
  frames: 0,

  init(){
    if (this.post || this.gl === false) return this.on;
    try {
      const c = document.createElement("canvas");
      this.post = SWBPost.create(c);
      this.gl = c;
      this.ro = document.createElement("canvas");
      this.roCtx = this.ro.getContext("2d");
      this.post.setBloom(SWBPost.SPREAD[SWBPost.SPREAD.DEFAULT]);
      this.post.setTrails(SWBPost.TRAILS[SWBPost.TRAILS.DEFAULT]);
      this.post.setGrade(SWBPost.GRADE[SWBPost.GRADE.DEFAULT]);
      this.on = true;
    } catch (e) {
      /* SAID OUT LOUD, ONCE. A silent fallback is how a clip ships missing an
         effect and nobody finds out until Rick watches it. */
      this.gl = false;
      this.on = false;
      try { console.warn("POSTFX off -- " + (e && e.message || e)); } catch (e2) {}
    }
    return this.on;
  },

  /* A fight's worth of trail history belongs to that fight. */
  reset(){ if (this.post) this.post.resetHistory(); this.frames = 0; },

  state(r){
    return {
      enabled: true,
      dt: CONFIG.physics.dt * 2,          /* one 60fps frame of sim time */
      frame: this.frames,
      rect: { x: r.pad * r.k, y: r.arenaTop * r.k,
              w: r.aw * r.k, h: r.ah * r.k },
      cine: (typeof CINE !== "undefined")
        ? { on: !!CINE.on, cut: !!CINE.cut, wash: CINE.wash || 0,
            bars: CINE.bars || 0, zoom: CINE.zoom || 1,
            flash: CINE.flash || 0, streak: CINE.streak || 0,
            tier: CINE.cut ? (CINE.cut.fatal ? "KILL" : "T" + CINE.cut.tier) : null,
            fatal: CINE.cut ? !!CINE.cut.fatal : false }
        : null,
      readouts: this.ro,
    };
  },

  /* TWO DRAWS AND A COMPOSITE. `busy` is what stops the two inner draws
     re-entering this method: they run at roMode 2 and 1, and the hook only
     fires at roMode 0. */
  frame(r, m){
    const cv = r.cv;
    this.busy = true;
    try {
      if (this.ro.width !== cv.width || this.ro.height !== cv.height){
        this.ro.width = cv.width; this.ro.height = cv.height;
      }
      const keep = r.roMode | 0;
      r.roMode = 2; r.draw(m);
      this.roCtx.clearRect(0, 0, this.ro.width, this.ro.height);
      this.roCtx.drawImage(cv, 0, 0);
      r.roMode = 1; r.draw(m);
      r.roMode = keep;
      this.frames++;
      if (this.post.render(cv, this.state(r))){
        /* Back into #cv, which stays the one canvas every tool reads --
           cinema_clip's toDataURL, verify's non-blank check, render_ab's
           hash. Nothing downstream has to learn a new name. */
        r.ctx.setTransform(1, 0, 0, 1, 0, 0);
        r.ctx.clearRect(0, 0, cv.width, cv.height);
        r.ctx.drawImage(this.gl, 0, 0);
      }
    } finally {
      this.busy = false;
    }
  },
};
'''

HOOK = r'''  draw(m){
    /* THE POST CHAIN. One hook, at the top of the one method every path into
       the picture goes through -- the live rAF loop, AC.__draw, and
       CINE.drawLerped all end up here -- so there is no second code path to
       keep in step. At roMode 0 with the chain on, POSTFX.frame draws this
       frame twice (readouts, then the world), composites, and puts the result
       back on #cv. `busy` stops those two inner draws re-entering. */
    if (POSTFX.on && !POSTFX.busy && (this.roMode | 0) === 0){
      POSTFX.frame(this, m);
      return;
    }
    const c = this.ctx;'''


def one(src: str, old: str, new: str, label: str) -> str:
    n = src.count(old)
    if n != 1:
        raise SystemExit(
            f"ANCHOR {label}: expected exactly 1 occurrence, found {n}.\n"
            f"  The source has moved under this builder. Do not weaken the\n"
            f"  anchor -- find out what changed.\n"
            f"  NOTE on Windows: if this says 0 for an anchor you can see in\n"
            f"  the file, check the read encoding before the anchor.\n"
            f"  anchor head: {old.splitlines()[0][:90]!r}")
    print(f"  ok    {label}")
    return src.replace(old, new, 1)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="../02-chain/sc-paradox-readouts.html")
    ap.add_argument("--out", default="../02-chain/sc-paradox-post.html")
    ap.add_argument("--off", action="store_true",
                    help="insert the chain but leave it switched off. For an "
                         "A/B build -- the picture is then identical to --src.")
    A = ap.parse_args()

    src_p = (HERE / A.src).resolve()
    out_p = (HERE / A.out).resolve()
    if out_p.name == PROTECTED:
        raise SystemExit("refusing to write the live build")
    if not src_p.exists():
        raise SystemExit(f"no such build: {src_p}")
    if not POST_JS.exists():
        raise SystemExit(f"no such module: {POST_JS}")

    s0 = src_p.read_text(encoding="utf-8")
    s = s0
    print("\nPOST BUILD -- the chain goes in, so the video gets what the app has")
    print(f"  src {src_p.name}  {hashlib.sha256(s0.encode()).hexdigest()[:16]}")

    if "POSTFX" in s0:
        raise SystemExit("this source already has POSTFX -- already built")
    if "this.roMode" not in s0 and "__ro2" not in s0:
        raise SystemExit(
            "this source has no readout split. Run readouts_build.py first --\n"
            "  without it the floats, tags and ult name go through the bloom\n"
            "  and are eaten on warm art. docs/RENDER-LAYERS.md §4.")

    module = POST_JS.read_text(encoding="utf-8")
    mod_hash = hashlib.sha256(module.encode()).hexdigest()[:16]

    # The module and the glue go in just before the renderer is constructed,
    # which is the last point at which nothing has drawn yet.
    anchor = "const renderer = new Renderer(cv);"
    block = ("/* ---- src/render/post.js, inlined by post_build.py. sha256:"
             + mod_hash + " ---- */\n"
             + module.rstrip() + "\n"
             + GLUE.strip() + "\n"
             + ("" if A.off else "POSTFX.init();\n")
             + "\n" + anchor)
    s = one(s, anchor, block, "the module and the glue")

    s = one(s, "  draw(m){\n    const c = this.ctx;", HOOK,
            "the hook in Renderer.draw")

    # A fight's trail history belongs to that fight.
    # THE APP MUST NOT RUN A SECOND CHAIN. Once the build has POSTFX, an
    # app-side overlay would post-process an already-post-processed frame,
    # and the app would show something the mp4 never contains -- the fault
    # this whole builder exists to close. Exported so the shell DRIVES this
    # one instead of owning a copy of it.
    s = one(s,
            "              newMatch, __inject, SFX, renderer, IC,",
            "              newMatch, __inject, SFX, renderer, IC,\n              /* THE ONE CHAIN. The app shell reaches this to set the\n                 pickers and the A/B toggle; it must never build a second\n                 one, because two chains means the app post-processes a\n                 frame the video already post-processed, and the app is\n                 then showing something the mp4 never contains. That is the\n                 exact fault this builder exists to close.\n                 See app/ui/post-dev.js. */\n              POSTFX,",
            "POSTFX on the export surface")

    s = one(s,
            "function newMatch(idA, idB, seedIn){",
            "function newMatch(idA, idB, seedIn){\n"
            "  /* the trail buffer belongs to the fight that filled it */\n"
            "  if (typeof POSTFX !== \"undefined\") POSTFX.reset();",
            "reset the history on a new match")

    s = STAMP.replace("%SRC%", src_p.name) + s

    if s.count("/*") != s.count("*/"):
        raise SystemExit(f"unbalanced block comments: {s.count('/*')} vs "
                         f"{s.count('*/')}")
    if s.count("{") != s.count("}"):
        raise SystemExit(f"unbalanced braces: {s.count('{')} vs {s.count('}')}")

    out_p.write_text(s, encoding="utf-8", newline="\n")
    print(f"  out {out_p.name}  {hashlib.sha256(s.encode()).hexdigest()[:16]}"
          f"   ({len(s) - len(s0):+d} bytes)"
          f"   chain {'OFF' if A.off else 'ON'}")
    print(f"  module sha256 {mod_hash}  (must match src/render/post.js)")
    print("\n  NEXT, and none of it is optional:")
    print(f"    python engine_ab.py --a {A.src} --b {A.out} --n 9")
    print(f"    python verify.py --game {A.out} --n 40")
    print(f"    python render_ab.py --a {A.src} --b {A.out}   # EXPECT A DIFF")
    print("    then frame_build.py to carry the tip forward.\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
