#!/usr/bin/env python3
"""THE READOUTS BECOME A SEPARATE LAYER. Default off; nothing moves.

    python readouts_build.py --src ../02-chain/sc-paradox-cine.html \
                             --out ../02-chain/sc-paradox-readouts.html

## Why

`docs/RENDER-LAYERS.md` §4 asked whether the damage floats and status tags
needed to come out of the world pass, and the Paradox filmstrip said no. The
Ironhail/Dawnbringer filmstrip at the SAME settings said yes: the `18` and its
SMITE tag, the `17` and its SMITE, and the ultimate-name callout are all eaten
by bloom and smeared by trails on art that is warm and broad rather than thin
blue lightning.

**A readout that survives one relic and not another is a layering mistake, not
a setting.** No threshold fixes it, because the light that destroys it comes
from the art NEXT to it. So the three readout layers have to be drawable apart
from the world, and the post chain composites them back on top, untouched.

## What this adds

One field, `renderer.roMode`, and nothing else:

    0   everything, exactly as before. THE DEFAULT.
    1   the world WITHOUT the three readouts -- the bloom's source
    2   ONLY the three readouts, on a cleared canvas -- composited back on top

Mode 2 keeps the whole camera path: the same scrunch, shake, punch, clip and
cinematic zoom the world was drawn with. That is the entire reason this is a
mode inside `draw()` rather than a second method that redraws the readouts
somewhere else -- the transform is fiddly, it is the director's, and a copy of
it would drift from the original the first time CINE changed.

## What it does NOT do

At `roMode` 0, which is what the live page and every existing tool get, not one
byte of behaviour changes. `engine_ab` must come back clean, and if it does not
then a guard below is wrong.

Two draws cost more than one. Mode 2 is cheap -- three text layers, no arena,
no fighters -- but it is not free, and tools/post_cost.py is where that gets
priced rather than assumed.
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
PROTECTED = "sundered-crown.html"

STAMP = ("<!-- GENERATED by readouts_build.py --src %SRC% "
         "— do not hand-edit or tune in place -->\n")

EDITS = [
    ("the ground and the HUD",
     '''    c.save();
    c.fillStyle = "#07050C";
    c.fillRect(0, 0, this.W, this.H);
    if (!this._introScene) this.drawHud(m);''',
     '''    /* THE READOUT LAYER SPLIT, and it needs no field declared: an unset
       `roMode` is undefined, and `undefined | 0` is 0, which is the mode that
       behaves exactly as this renderer always has. Every existing caller gets
       it without knowing this exists.

         0  everything, as before. THE DEFAULT.
         1  the world WITHOUT the damage floats, the status tags and the
            ultimate-name callout -- the bloom's source.
         2  ONLY those three, on a cleared canvas -- composited back on top.

       It exists because the light that destroys a readout comes from the art
       NEXT to it, so no threshold can save it. docs/RENDER-LAYERS.md §4. */
    const __ro = this.roMode | 0, __ro2 = __ro === 2, __ro1 = __ro === 1;
    c.save();
    if (__ro2){
      /* Cleared, not filled: the readouts have to arrive on transparency so
         the compositor can put them over a picture rather than over a black
         rectangle with three words in it. */
      c.clearRect(0, 0, this.W, this.H);
    } else {
      c.fillStyle = "#07050C";
      c.fillRect(0, 0, this.W, this.H);
      if (!this._introScene) this.drawHud(m);
    }'''),

    ("the hall",
     '''    this.drawArena(m);
    c.scale(this.scale, this.scale);
    this.drawMotes(m);''',
     '''    if (!__ro2) this.drawArena(m);
    c.scale(this.scale, this.scale);
    if (!__ro2){
    this.drawMotes(m);'''),

    ("the world, up to the ult name",
     '''    /* and a lash is a strike, so it goes over the thing it struck */
    this.drawVines(m, true);
    this.drawUltName(m);
    this.drawUltOver(m);
    this.drawRings(m);
    this.drawFloats(m);
    this.drawTags(m);
    if (typeof CINE !== "undefined" && CINE.on && CINE.streak > 0.01)
      this.drawCineStreaks(m);
    c.restore();''',
     '''    /* and a lash is a strike, so it goes over the thing it struck */
    this.drawVines(m, true);
    }
    /* THE THREE READOUTS. Emissive-looking, but they are text: a number, a
       status name, and the ultimate's name. They read or they do not. */
    if (!__ro1) this.drawUltName(m);
    if (!__ro2){
    this.drawUltOver(m);
    this.drawRings(m);
    }
    if (!__ro1){
    this.drawFloats(m);
    this.drawTags(m);
    }
    if (!__ro2 && typeof CINE !== "undefined" && CINE.on && CINE.streak > 0.01)
      this.drawCineStreaks(m);
    c.restore();'''),

    ("everything after the arena",
     '''    if (typeof CINE !== "undefined" && CINE.on) this.drawCine(m);

    if (m.finisher > 0){''',
     '''    if (!__ro2 && typeof CINE !== "undefined" && CINE.on) this.drawCine(m);

    if (!__ro2 && m.finisher > 0){'''),

    ("the chrome",
     '''    this.drawArenaFrame(m);
    this.drawClock(m);
    this.drawBanner(m);
    if (!this._introScene) this.drawFooter(m);
    this.drawTug(m);
    if (m.over) this.drawResult(m);''',
     '''    if (!__ro2){
    this.drawArenaFrame(m);
    this.drawClock(m);
    this.drawBanner(m);
    if (!this._introScene) this.drawFooter(m);
    this.drawTug(m);
    if (m.over) this.drawResult(m);
    }'''),

    ("the scrunch panel",
     '''    if (__sv){
      Object.assign(this, __sv);
      c.setTransform(this.k, 0, 0, this.k, 0, 0);
      this.drawScrunchPanel(m, __sk);
    }''',
     '''    if (__sv){
      Object.assign(this, __sv);
      c.setTransform(this.k, 0, 0, this.k, 0, 0);
      if (!__ro2) this.drawScrunchPanel(m, __sk);
    }'''),
]


def one(src: str, old: str, new: str, label: str) -> str:
    n = src.count(old)
    if n != 1:
        raise SystemExit(
            f"ANCHOR {label}: expected exactly 1 occurrence, found {n}.\n"
            f"  The source has moved under this builder. Do not weaken the\n"
            f"  anchor -- find out what changed.\n"
            f"  NOTE on Windows: if this says 0 for an anchor you can see in\n"
            f"  the file, check the read encoding before you check the anchor.\n"
            f"  anchor head: {old.splitlines()[0][:90]!r}")
    print(f"  ok    {label}")
    return src.replace(old, new, 1)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="../02-chain/sc-paradox-cine.html")
    ap.add_argument("--out", default="../02-chain/sc-paradox-readouts.html")
    A = ap.parse_args()

    src_p = (HERE / A.src).resolve()
    out_p = (HERE / A.out).resolve()
    if out_p.name == PROTECTED:
        raise SystemExit("refusing to write the live build")
    if not src_p.exists():
        raise SystemExit(f"no such build: {src_p}")

    s0 = src_p.read_text(encoding="utf-8")
    s = s0
    print("\nREADOUTS BUILD -- the three text layers become their own pass")
    print(f"  src {src_p.name}  {hashlib.sha256(s0.encode()).hexdigest()[:16]}")
    if "__ro2" in s0:
        raise SystemExit("this source already has the split -- already built")

    for label, old, new in EDITS:
        s = one(s, old, new, label)

    s = STAMP.replace("%SRC%", src_p.name) + s

    # A builder should syntax-check its own output (CLAUDE.md §4.11). Braces
    # matter more than usual here: every edit above opens or closes one.
    if s.count("/*") != s.count("*/"):
        raise SystemExit(f"unbalanced block comments: {s.count('/*')} vs "
                         f"{s.count('*/')}")
    if s.count("{") != s.count("}"):
        raise SystemExit(f"unbalanced braces: {s.count('{')} vs {s.count('}')} "
                         f"(source had {s0.count('{')} vs {s0.count('}')})")

    out_p.write_text(s, encoding="utf-8", newline="\n")
    print(f"  out {out_p.name}  {hashlib.sha256(s.encode()).hexdigest()[:16]}"
          f"   ({len(s) - len(s0):+d} bytes)")
    print("\n  NEXT, and none of it is optional:")
    print(f"    python engine_ab.py --a {A.src} --b {A.out} --n 9")
    print(f"    python verify.py --game {A.out} --n 40")
    print("    then frame_build.py to carry the tip forward.\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
