#!/usr/bin/env python
"""THE STAFF CARRY -- the seven staves re-applied onto another line's tip.

    python staff_carry.py --src ../02-chain/sc-coldiron-temper-fx.html --out ../02-chain/sc-staves-coldiron.html
    python staff_carry.py --src <tip> --out <scratch>/x.html --keep <scratch>/links   # every link kept

The staff row was built on yert as a BRANCH off sc-leaf (Culverin v96 ->
Nightglass v91), beside the design batch's line on DESKTOP-DERRAFT. Rick,
2026-09-27, off the seven clips: "looks good get it in the game". The two
lines meet by running every staff builder's every stage, in the row's order,
with `--src` on the batch line's tip -- the builders are the numbers' only
home (CLAUDE.md §4.9), so the carry is nothing but them, re-run. Culverin's
builder was written to accept either line; the other six chain on the staff
before them.

THE BATCH LINE'S TIP IS NOT MOVED. It is still being built on DESKTOP-DERRAFT
(its relics land one at a time), and moving another session's base mid-build
is rule 0 arriving through the chain. The carried link is a NEW link on top of
it; when the batch line moves on, this is re-run on its new tip.

The intermediate links go to a temporary directory (or `--keep`); only the
last is written to `--out`, stamped with this carry. Each builder's own
checks, syntax check and RNG refusal run on every stage, exactly as they did
on the staff branch.
"""
from __future__ import annotations
import argparse, hashlib, pathlib, shutil, subprocess, sys, tempfile

HERE = pathlib.Path(__file__).parent
sys.path.insert(0, str(HERE))
from staffkit import syntax_check

# The row, in v89 §7's order, every stage each builder has.
ROW = [
    ("culverin_build.py", ["1", "2", "3", "5", "6"]),
    ("briarwand_build.py", ["1", "2", "3", "5", "6"]),
    ("cipher_build.py", ["1", "2", "3", "5", "6"]),
    ("watchlight_build.py", ["1", "2", "3", "6"]),
    ("crozier_build.py", ["1", "2", "3", "5", "6"]),
    ("bloodwick_build.py", ["1", "2", "3", "4", "5", "6"]),
    ("nightglass_build.py", ["1", "2", "3", "5", "6"]),
]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True, help="the other line's tip")
    ap.add_argument("--out", required=True)
    ap.add_argument("--keep", default=None, help="a directory to keep every intermediate link in")
    A = ap.parse_args()
    src = (HERE / A.src).resolve()
    out = (HERE / A.out).resolve()
    if out.exists():
        raise SystemExit(f"refusing to overwrite {out.name} -- a link is written once")
    if not src.exists():
        raise SystemExit(f"no such build: {src}")
    work = pathlib.Path(A.keep).resolve() if A.keep else pathlib.Path(tempfile.mkdtemp(prefix="staffcarry-"))
    work.mkdir(parents=True, exist_ok=True)
    s0 = src.read_text(encoding="utf-8")
    print(f"THE STAFF CARRY onto {src.name}  {hashlib.sha256(s0.encode()).hexdigest()[:16]}")
    prev, n = src, 0
    for builder, stages in ROW:
        for st in stages:
            n += 1
            link = work / f"{n:02d}-{builder.split('_')[0]}-s{st}.html"
            if link.exists():
                link.unlink()
            r = subprocess.run([sys.executable, str(HERE / builder), "--stage", st,
                                "--src", str(prev), "--out", str(link)],
                               cwd=HERE, capture_output=True, text=True, encoding="utf-8")
            tail = [l for l in r.stdout.splitlines() if l.strip().startswith("out ")]
            if r.returncode != 0 or not link.exists():
                print(r.stdout[-3000:]); print(r.stderr[-3000:])
                raise SystemExit(f"STOPPED at {builder} --stage {st}: the carry does not hold there")
            print(f"  ok  {builder:<22} stage {st}   {tail[-1].strip() if tail else ''}")
            prev = link
    body = prev.read_text(encoding="utf-8")
    first, rest = body.split("\n", 1)
    if not first.startswith("<!-- GENERATED by"):
        raise SystemExit("the last link carries no stamp")
    stamp = (f"<!-- GENERATED by staff_carry.py --src {src.name} (the seven staff builders, "
             f"every stage, in v89 §7's order; last: {first[len('<!-- GENERATED by '):-len(' -->')]}) -->")
    s = stamp + "\n" + rest
    syntax_check(s, out.name)
    out.write_text(s, encoding="utf-8", newline="\n")
    print(f"\n  out {out.name}  {hashlib.sha256(s.encode()).hexdigest()[:16]}   "
          f"({len(s) - len(s0):+d} chars over the tip, written LF)")
    if not A.keep:
        shutil.rmtree(work, ignore_errors=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
