#!/usr/bin/env python3
"""CARRY THE NEAR-WHITE BODIES' CORRECTED SET-PIECES TO THE TIP. Art only.

    python whiteball_build.py --src ../02-chain/sc-paradox-readouts.html \
                              --out ../02-chain/sc-paradox-dawn.html
    python post_build.py --src ../02-chain/sc-paradox-dawn.html \
                         --out ../02-chain/sc-paradox-frame.html

WAS daybreak_annulus_build.py. Renamed when Aureole joined it: the fault is
not Daybreak's alone and the fix is not an annulus. Both relics paint
`lighter` over a body that is already near white -- Daybreak with a corona
centred on it, Benediction with a lance that starts at the caster's middle and
heal rings that contract to r=16 against a ball radius of 34. One principle,
three shapes: START THE LIGHT AT THE SHELL.

WHY THIS EXISTS RATHER THAN A REBUILD FROM THE OWNING BUILDERS
--------------------------------------------------------------
`ultdawn_build.py` and `ultart2_build.py` OWN this art and have been corrected
-- that is where CLAUDE.md 4.9 says a change lives, and any future rebuild
from sc-crucible carries it. But the chain from there to the tip cannot be
replayed: most files in 02-chain/ stamp `GENERATED by introcard_build.py` with
NO `--src`, so the build graph is not reconstructible from the tree, and
reconstructing it by guess on the build of record is how a session invalidates
the whole history. So the corrected blocks are carried forward one link.

THERE IS EXACTLY ONE COPY OF EACH SET-PIECE AND THIS FILE IS NOT IT. Daybreak's
block is imported from ultdawn_build. Benediction's is SLICED OUT of
ultart2_build's `OVER` literal, which carries all six of the last relics in one
string and so cannot be imported by name. The brace-matching replace is
imported too. Restating any of it here is the drift CLAUDE.md 4.10 warns about.

THIS CHANGES THE PICTURE AND NOTHING ELSE. `drawUltOver` is presentation --
nothing in Fighter, Match or Sfx reads it -- so engine_ab against the previous
tip must come back IDENTICAL on all 25 relics. If it does not, this build is
wrong and the diff is the proof.
"""
from __future__ import annotations
import argparse, pathlib, sys

HERE = pathlib.Path(__file__).parent
sys.path.insert(0, str(HERE))

from ultdawn_build import OVER_NEW, replace_block
import ultart2_build

STAMP = ("<!-- GENERATED by whiteball_build.py --src %SRC% "
         "— do not hand-edit or tune in place -->\n")


def _slice(s: str, marker: str) -> str:
    """One `else if` block out of a builder's multi-relic literal, brace-matched."""
    i = s.index(marker)
    j = s.index("{", i)
    depth, k = 0, j
    while k < len(s):
        if s[k] == "{":
            depth += 1
        elif s[k] == "}":
            depth -= 1
            if depth == 0:
                break
        k += 1
    return s[i:k + 1]


# Named *_NEW on purpose: chain_audit.py finds a builder's inserts by that
# suffix. It reads builder SOURCE first and falls back to importing -- these
# are computed, so only the import path sees them, which is the fallback this
# file's predecessor caused to be written.
#
# ultdawn's block opens with `if (u.w === ...)`; at the tip it is an `else if`.
CORONA_NEW = OVER_NEW.replace('    if (u.w === "dawnbringer"){',
                              '    else if (u.w === "dawnbringer"){', 1)

# `else if (u.w === "aureole")` appears TWICE in the renderer -- the lit ground
# UNDER the blessing, and this one over it. The comment line is what separates
# them; matching on the bare `else if` would have silently rewritten the floor
# art instead and the sheet would have looked unchanged.
BENEDICTION_MARK = ('    /* ---- Benediction: sent OUT, not called down '
                    '---------------------------- */\n'
                    '    else if (u.w === "aureole"){')
BENEDICTION_NEW = _slice(ultart2_build.OVER, BENEDICTION_MARK)

DAYBREAK_MARK = ('    /* ---- Daybreak: white heat radiating off the whole relic '
                 '------------- */\n    else if (u.w === "dawnbringer"){')

# (name, marker in --src, corrected block, a string that proves it is already done)
CARRIES = [
    ("Daybreak corona", DAYBREAK_MARK, CORONA_NEW,
     'c.arc(src.x, src.y, R * 0.94, TAU, 0, true)'),
    ("Benediction lance and heal rings", BENEDICTION_MARK, BENEDICTION_NEW,
     'const R0 = CONFIG.physics.ballR * 1.06;'),
]


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", default="../02-chain/sc-paradox-readouts.html")
    ap.add_argument("--out", default="../02-chain/sc-paradox-dawn.html")
    A = ap.parse_args()

    src = (HERE / A.src).resolve()
    out = (HERE / A.out).resolve()
    s = src.read_text(encoding="utf8")

    s2 = s
    for name, mark, block, done in CARRIES:
        if mark not in s2:
            sys.exit(f"! {name}: marker is not in --src in the shape expected. "
                     f"Nothing written.")
        if done in s2:
            sys.exit(f"! {name}: --src already carries this. Nothing to do.")
        before = s2
        s2 = replace_block(s2, mark, block, name)
        if s2 == before:
            sys.exit(f"! {name}: replace_block was a no-op. Nothing written.")

    s2 = STAMP.replace("%SRC%", src.name) + s2

    # 4.11 -- A BUILDER SHOULD SYNTAX-CHECK ITS OWN OUTPUT. An unbalanced brace
    # surfaces only as a twenty-second Playwright timeout somewhere else.
    body = s2[s2.index("<script"):]
    if body.count("{") != body.count("}"):
        sys.exit("! brace count in the output does not balance. Nothing written.")

    out.write_text(s2, encoding="utf8")
    print(f"  {out.name}")
    for name, _, _, done in CARRIES:
        print(f"    {s2.count(done)}x  {name}")


if __name__ == "__main__":
    main()
